import {
  Agent,
  ControllerSnapshot,
  MemoryEntry,
  MessageRecord,
  MessagingSnapshot,
  Skill,
  Task,
  Workflow,
  WorkLog,
} from './shared-services/interfaces';

export const MOCK_AGENTS: Agent[] = [
  {
    id: 'system-engineer-agent',
    name: 'System Engineer Agent',
    role: 'Primary implementation agent for feature work, fixes, integrations, and validation.',
    status: 'implementing',
    summary:
      'Reads context, plans the change, edits source, verifies behavior, and produces a concise completion report.',
    workflow: 'standard-engineering',
    tools: ['read-file', 'update-file', 'run-tests', 'browser-check', 'git-publish'],
    aliases: ['system-engineer', 'implementation-agent'],
    instructionsPath: 'agent-config/agents/system-engineer-agent/instructions.md',
    skills: ['context-standard', 'python-coder', 'ui-validation', 'memory-manager'],
    history: [
      'Resolved article-site navigation polish and GitHub Pages publish flow.',
      'Adapted controller UI to static mock data for public demo pages.',
      'Verified route rendering through browser and production build checks.',
    ],
    performance: [
      { label: 'Recent runs', value: '42' },
      { label: 'Clean finishes', value: '91%' },
      { label: 'Avg validation', value: '3 checks' },
    ],
  },
  {
    id: 'planner-agent',
    name: 'Planner Agent',
    role: 'Breaks large requests into ordered, reviewable task plans.',
    status: 'available',
    summary:
      'Turns broad goals into concrete steps, dependencies, acceptance criteria, and suggested owners.',
    workflow: 'planning-first',
    tools: ['read-context', 'create-plan', 'split-tasks'],
    aliases: ['planner', 'task-breakdown'],
    instructionsPath: 'agent-config/agents/planner-agent/instructions.md',
    skills: ['context-standard', 'architecture-review'],
    history: [
      'Split controller-plane work into backend, UI, runtime, and publishing tasks.',
      'Flagged approval gates before any durable execution handoff.',
    ],
    performance: [
      { label: 'Plans accepted', value: '28' },
      { label: 'Rework avoided', value: '76%' },
      { label: 'Avg tasks', value: '5.4' },
    ],
  },
  {
    id: 'analysis-agent',
    name: 'Analysis Agent',
    role: 'Read-mostly investigator for root cause and system behavior.',
    status: 'available',
    summary:
      'Inspects evidence, compares likely causes, and hands a bounded diagnosis back to the working agent.',
    workflow: 'deep-investigation',
    tools: ['search-source', 'read-logs', 'summarize-evidence'],
    aliases: ['analysis', 'second-reader'],
    instructionsPath: 'agent-config/agents/analysis-agent/instructions.md',
    skills: ['context-deep', 'failure-analysis'],
    history: [
      'Separated sandbox network failures from real backend startup failures.',
      'Confirmed stale API health data before recommending a retry path.',
    ],
    performance: [
      { label: 'Findings', value: '19' },
      { label: 'False leads cut', value: '63%' },
      { label: 'Avg depth', value: 'medium' },
    ],
  },
  {
    id: 'agent-ui-debugger',
    name: 'Agent UI Debugger',
    role: 'Browser validation worker for screenshots, console errors, and UI state.',
    status: 'queued',
    summary:
      'Receives a debug request through messaging, opens the target route, captures evidence, and reports actionable issues.',
    workflow: 'ui-debug-request',
    tools: ['open-browser', 'capture-screenshot', 'inspect-console', 'network-summary'],
    aliases: ['ui-debugger', 'browser-agent'],
    instructionsPath: 'agent-config/agents/agent-ui-debugger/instructions.md',
    skills: ['ui-validation', 'browser-evidence'],
    history: [
      'Captured controller route screenshots after navigation changes.',
      'Reported failed API calls with endpoint, method, and response detail.',
    ],
    performance: [
      { label: 'Screenshots', value: '116' },
      { label: 'Useful reports', value: '94%' },
      { label: 'Avg wait', value: '1.2s' },
    ],
  },
  {
    id: 'strategy-memory-analyzer',
    name: 'Strategy Memory Analyzer',
    role: 'Turns post-work feedback into bounded memory proposals.',
    status: 'available',
    summary:
      'Looks at feedback, completed runs, and durable evidence before suggesting small changes to future agent behavior.',
    workflow: 'feedback-to-memory',
    tools: ['read-feedback', 'compare-run', 'write-memory-candidate'],
    aliases: ['strategy-memory', 'feedback-agent'],
    instructionsPath: 'agent-config/agents/strategy-memory-analyzer/instructions.md',
    skills: ['memory-manager', 'feedback-analysis'],
    history: [
      'Captured preference for browser-backed UI verification.',
      'Reduced repeated final-answer drift by recording concrete validation language.',
    ],
    performance: [
      { label: 'Candidates', value: '14' },
      { label: 'Accepted', value: '10' },
      { label: 'Scope', value: 'bounded' },
    ],
  },
  {
    id: 'root-agent',
    name: 'Root Agent',
    role: 'Narrow infrastructure steward for bootstrap, recovery, and path drift.',
    status: 'available',
    summary:
      'Protects source-of-truth files, controller attachment, runtime startup, and system-wide migration boundaries.',
    workflow: 'platform-recovery',
    tools: ['health-check', 'path-map', 'controller-startup', 'repo-audit'],
    aliases: ['root', 'platform-steward'],
    instructionsPath: 'agent-config/agents/root-agent/instructions.md',
    skills: ['context-deep', 'system-health'],
    history: [
      'Diagnosed low-port binding restrictions during controller startup.',
      'Preserved durable agent state while cleaning obsolete compatibility paths.',
    ],
    performance: [
      { label: 'Recoveries', value: '8' },
      { label: 'Drift checks', value: '31' },
      { label: 'Risk level', value: 'low' },
    ],
  },
];

export const MOCK_SKILLS: Skill[] = [
  {
    id: 'context-standard',
    name: 'Context Standard',
    category: 'engineering',
    summary: 'Fast context retrieval for ordinary feature and bug work.',
    content:
      'Read the nearest project instructions, search current source, open the smallest useful files, and stop retrieving once the implementation boundary is clear.',
    path: 'agent-config/skills/context-standard/SKILL.md',
    assignedAgents: ['system-engineer-agent', 'planner-agent'],
  },
  {
    id: 'context-deep',
    name: 'Context Deep',
    category: 'architecture',
    summary: 'Progressive investigation for large incidents and migrations.',
    content:
      'Retrieve architecture, history, runtime evidence, and decision records only when each source answers a concrete question.',
    path: 'agent-config/skills/context-deep/SKILL.md',
    assignedAgents: ['analysis-agent', 'root-agent'],
  },
  {
    id: 'ui-validation',
    name: 'UI Validation',
    category: 'frontend',
    summary: 'Browser evidence for visual, routing, and network behavior.',
    content:
      'Open the route, inspect rendered text, collect console/network evidence, and verify that the UI is using real data instead of an empty shell.',
    path: 'agent-config/skills/ui-validation/SKILL.md',
    assignedAgents: ['system-engineer-agent', 'agent-ui-debugger'],
  },
  {
    id: 'memory-manager',
    name: 'Memory Manager',
    category: 'runtime',
    summary: 'Keeps durable learning small, verified, and useful.',
    content:
      'Store only hard-to-rediscover lessons after substantial work, and prefer concrete failure shields over vague preferences.',
    path: 'agent-config/skills/memory-manager/SKILL.md',
    assignedAgents: ['strategy-memory-analyzer', 'system-engineer-agent'],
  },
  {
    id: 'python-coder',
    name: 'Python Coder',
    category: 'implementation',
    summary: 'Python structure, tests, compile checks, and code-map hygiene.',
    content:
      'Keep ARCHITECTURE.md and code-map.yaml synchronized with Python structure changes, then run compile and test checks.',
    path: 'agent-config/skills/python-coder/SKILL.md',
    assignedAgents: ['system-engineer-agent'],
  },
  {
    id: 'browser-evidence',
    name: 'Browser Evidence',
    category: 'debugging',
    summary: 'Captures screenshots, accessibility tree, and failed requests.',
    content:
      'Collect route URL, visible state, console messages, screenshots when useful, and actionable failed XHR/fetch calls.',
    path: 'agent-config/skills/browser-evidence/SKILL.md',
    assignedAgents: ['agent-ui-debugger'],
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'task-1042',
    title: 'Publish controller plane UI demo',
    summary: 'Copy the controller UI into the article site and back it with static mock data.',
    status: 'implementing',
    label: 'frontend',
    date: 'Sep 13, 2026',
    tokens: 14820,
    plan:
      '1. Copy controller components into the article app.\n2. Replace live controller API calls with static mock state.\n3. Add an article-nav callout route.\n4. Build, preview, and push the GitHub Pages output.',
    owner: 'system-engineer-agent',
    agentId: 'system-engineer-agent',
    duration: '38m',
    prompt: 'Create a public mock version of the controller plane UI inside my article site.',
    messageId: 'msg-9001',
    runId: 'run-article-demo-2026-09-13',
    sessionId: 'session-article-site',
    createdAt: '2026-09-13T17:26:00Z',
    updatedAt: '2026-09-13T18:04:00Z',
    events: [
      {
        ts: '2026-09-13T17:26:02Z',
        type: 'task.created',
        status: 'awaiting implementation',
        message: 'Controller demo request accepted from article-site nav.',
      },
      {
        ts: '2026-09-13T17:31:28Z',
        type: 'context.resolved',
        status: 'implementing',
        message: 'Article shell and controller component boundaries identified.',
      },
      {
        ts: '2026-09-13T17:54:12Z',
        type: 'ui.demo.seeded',
        status: 'implementing',
        message: 'Mock tasks, agents, memory, logs, workflows, and messages prepared.',
      },
    ],
    source: 'controller',
    planId: 'plan-controller-demo',
    planTitle: 'Article-site controller demo',
    taskPath: '.agent-state/task/task-1042.yaml',
    files: ['src/app/controller-demo/**', 'src/app/article-page.component.ts'],
    acceptanceCriteria: [
      'Demo route loads on GitHub Pages without a backend.',
      'Article nav contains a full-width controller plane button.',
      'All controller sections contain realistic mock data.',
    ],
  },
  {
    id: 'task-1039',
    title: 'Review message bus error handoff',
    summary: 'Trace how failed tool calls become durable error records and follow-up tasks.',
    status: 'awaiting implementation',
    label: 'runtime',
    date: 'Sep 13, 2026',
    tokens: 6320,
    plan:
      'Inspect message event schema, replay a failed tool call, and verify the resulting operational-error record and rework task.',
    owner: 'analysis-agent',
    agentId: 'analysis-agent',
    duration: 'queued',
    prompt: 'Explain where failed tool calls are stored and how another agent can pick them up.',
    messageId: 'msg-9002',
    createdAt: '2026-09-13T16:49:00Z',
    updatedAt: '2026-09-13T16:50:11Z',
    events: [
      {
        ts: '2026-09-13T16:49:00Z',
        type: 'message.received',
        status: 'pending',
        message: 'Pending analysis request is waiting for explicit start.',
      },
    ],
    source: 'controller',
    dependsOn: ['task-1042'],
  },
  {
    id: 'task-1035',
    title: 'Run UI debugger on controller shell',
    summary: 'Open the controller route, capture rendered state, and report failed API calls.',
    status: 'complete',
    label: 'debug',
    date: 'Sep 12, 2026',
    tokens: 9280,
    plan:
      'Send a ui_debug_request message, wait for browser evidence, summarize screenshot, console, and network findings.',
    owner: 'agent-ui-debugger',
    agentId: 'agent-ui-debugger',
    duration: '12m',
    prompt: 'Validate that the controller UI renders current repository data.',
    messageId: 'msg-8840',
    runId: 'run-ui-debug-8840',
    sessionId: 'session-controller-check',
    createdAt: '2026-09-12T21:10:00Z',
    updatedAt: '2026-09-12T21:22:00Z',
    events: [
      {
        ts: '2026-09-12T21:12:00Z',
        type: 'browser.opened',
        status: 'implementing',
        message: 'Opened task-thread route in Chrome.',
      },
      {
        ts: '2026-09-12T21:22:00Z',
        type: 'task.completed',
        status: 'complete',
        message: 'Rendered real agent and workflow data from the controller API.',
      },
    ],
    source: 'controller',
  },
  {
    id: 'task-1028',
    title: 'Memory feedback proposal',
    summary: 'Turn post-work feedback into a small durable memory candidate.',
    status: 'need rework',
    label: 'memory',
    date: 'Sep 11, 2026',
    tokens: 5480,
    plan:
      'Compare user feedback with completed run evidence, produce one scoped memory candidate, and wait for operator approval.',
    owner: 'strategy-memory-analyzer',
    agentId: 'strategy-memory-analyzer',
    duration: '9m',
    prompt: 'Remember that article diagrams should render full height without scrollbars.',
    messageId: 'msg-8715',
    runId: 'run-memory-feedback-8715',
    sessionId: 'session-memory-loop',
    createdAt: '2026-09-11T20:05:00Z',
    updatedAt: '2026-09-11T20:14:00Z',
    events: [
      {
        ts: '2026-09-11T20:14:00Z',
        type: 'feedback.needs_more_specificity',
        status: 'need rework',
        message: 'Candidate was too broad; needs exact visual constraint and validation path.',
      },
    ],
    source: 'controller',
  },
  {
    id: 'task-1019',
    title: 'Controller startup recovery',
    summary: 'Diagnose low-port startup failures and choose a local high-port fallback.',
    status: 'complete',
    label: 'ops',
    date: 'Sep 10, 2026',
    tokens: 11440,
    plan:
      'Build backend, start services, probe health endpoints, identify EACCES, and document safe high-port startup.',
    owner: 'root-agent',
    agentId: 'root-agent',
    duration: '24m',
    prompt: 'Run the controller plane application.',
    messageId: 'msg-8412',
    runId: 'run-controller-startup-8412',
    sessionId: 'session-controller-start',
    createdAt: '2026-09-10T18:30:00Z',
    updatedAt: '2026-09-10T18:54:00Z',
    events: [
      {
        ts: '2026-09-10T18:42:00Z',
        type: 'port.denied',
        status: 'implementing',
        message: 'localhost:1002 failed with EACCES on this host.',
      },
      {
        ts: '2026-09-10T18:54:00Z',
        type: 'task.completed',
        status: 'complete',
        message: 'Controller verified on high local ports with browser evidence.',
      },
    ],
    source: 'controller',
  },
];

export const MOCK_WORKFLOWS: Workflow[] = [
  {
    id: 'standard-engineering',
    name: 'Standard Engineering',
    status: 'ready',
    runs: '42 recent runs',
    owner: 'system-engineer-agent',
    description: 'Default path for normal feature work, bug fixes, UI/backend changes, and verification.',
    phase: 'implementation',
    steps: [
      { id: 'intake', name: 'Read request and repo instructions', uses: 'context', agent: 'system-engineer-agent' },
      { id: 'resolve-context', name: 'Find the smallest useful source boundary', uses: 'read-source' },
      { id: 'edit', name: 'Apply scoped source changes', uses: 'update-file' },
      { id: 'verify', name: 'Run compile, tests, and browser checks', uses: 'run-workflow' },
      { id: 'publish', name: 'Commit and push when requested', uses: 'git-publish' },
    ],
  },
  {
    id: 'ui-debug-request',
    name: 'UI Debug Request',
    status: 'ready',
    runs: '18 recent runs',
    owner: 'agent-ui-debugger',
    description: 'Browser evidence workflow for route rendering, console problems, and failed network calls.',
    phase: 'debugging',
    steps: [
      { id: 'open', name: 'Open target URL in browser', uses: 'browser-open', tool: 'chrome' },
      { id: 'settle', name: 'Wait for UI to settle', uses: 'wait' },
      { id: 'inspect', name: 'Collect visible state and accessibility tree', uses: 'browser-inspect' },
      { id: 'report', name: 'Return screenshot and actionable failed requests', uses: 'message-reply' },
    ],
  },
  {
    id: 'feedback-to-memory',
    name: 'Feedback To Memory',
    status: 'ready',
    runs: '14 recent runs',
    owner: 'strategy-memory-analyzer',
    description: 'Converts operator feedback into precise memory candidates after evidence review.',
    phase: 'learning',
    steps: [
      { id: 'feedback', name: 'Read feedback artifact', uses: 'read-file' },
      { id: 'evidence', name: 'Compare completed run evidence', uses: 'search-source' },
      { id: 'candidate', name: 'Write bounded memory candidate', uses: 'write-file' },
      { id: 'approval', name: 'Wait for operator approval', uses: 'approval-gate' },
    ],
  },
  {
    id: 'controller-startup',
    name: 'Controller Startup',
    status: 'ready',
    runs: '9 recent runs',
    owner: 'root-agent',
    description: 'Builds and starts the controller backend/frontend, then probes health and browser state.',
    phase: 'operations',
    steps: [
      { id: 'backend-build', name: 'Compile Nest controller API', uses: 'command', command: 'npm run backend:build' },
      { id: 'backend-start', name: 'Start controller API', uses: 'command', command: 'npm run backend:start' },
      { id: 'frontend-start', name: 'Start Angular UI', uses: 'command', command: 'npm start' },
      { id: 'health', name: 'Probe snapshot and browser route', uses: 'health-check' },
    ],
  },
  {
    id: 'deep-investigation',
    name: 'Deep Investigation',
    status: 'ready',
    runs: '11 recent runs',
    owner: 'analysis-agent',
    description: 'Architecture-aware investigation for difficult failures, migrations, and state issues.',
    phase: 'analysis',
    steps: [
      { id: 'scope', name: 'Define the question being answered', uses: 'context' },
      { id: 'evidence', name: 'Gather logs, source, and history only as needed', uses: 'read-source' },
      { id: 'compare', name: 'Compare likely root causes', uses: 'analysis' },
      { id: 'handoff', name: 'Hand bounded findings to implementation owner', uses: 'message-reply' },
    ],
  },
];

export const MOCK_MEMORY: MemoryEntry[] = [
  {
    id: 'mem-visual-validation',
    title: 'Use browser evidence for article-site UI changes',
    kind: 'preference',
    status: 'active',
    updated: '2026-09-13',
    excerpt:
      'After changing article-site layout or routes, verify with a browser route check and note visible evidence, not just build output.',
    content:
      'When publishing article-site UI changes, run the production build, preview the output, open the route in a browser, and confirm the visible state includes the requested labels or controls.',
    path: '.agent-state/cache/memory/records/article-ui-validation.yaml',
    runId: 'run-article-demo-2026-09-13',
    sessionId: 'session-article-site',
    tags: ['articles', 'ui', 'validation'],
    metadata: { confidence: 0.92, source: 'feedback-loop', owner: 'strategy-memory-analyzer' },
  },
  {
    id: 'mem-controller-ports',
    title: 'Controller default ports may be denied locally',
    kind: 'failure-shield',
    status: 'active',
    updated: '2026-09-12',
    excerpt:
      'If localhost:1001 or localhost:1002 fail with EACCES, use host-specific high ports and wire the UI backend override.',
    content:
      'The controller API defaults to 1002 and Angular defaults to 1001. Some local environments deny those ports. Confirm with endpoint probes before claiming the app is down.',
    path: '.agent-state/cache/memory/records/controller-port-eacces.yaml',
    runId: 'run-controller-startup-8412',
    sessionId: 'session-controller-start',
    tags: ['controller', 'startup', 'ports'],
    metadata: { failure: 'EACCES', fallbackBackend: 3102, fallbackFrontend: 3101 },
  },
  {
    id: 'mem-diagram-height',
    title: 'Article diagrams should render full height',
    kind: 'preference',
    status: 'active',
    updated: '2026-09-11',
    excerpt:
      'Diagrams embedded in articles should not show internal scrollbars; the frame should reveal the full diagram.',
    content:
      'Use fixed diagram frame sizes and preview at desktop and mobile widths after adding new diagrams to article pages.',
    path: '.agent-state/cache/memory/records/article-diagram-height.yaml',
    tags: ['articles', 'diagrams', 'layout'],
    metadata: { appliesTo: 'my-articles', validation: 'browser-preview' },
  },
  {
    id: 'mem-message-runtime',
    title: 'Runtime owns execution state',
    kind: 'architecture',
    status: 'active',
    updated: '2026-09-10',
    excerpt:
      'The controller is a data and operator surface; runtime owns workflow resolution, events, finalization, and memory extraction.',
    content:
      'Do not duplicate runtime state in clients. Use RuntimeEvent and durable message artifacts as the source of truth for live progress and post-run records.',
    path: '.agent-state/cache/memory/records/runtime-ownership.yaml',
    tags: ['runtime', 'controller', 'events'],
    metadata: { owner: 'system-engineer-agent' },
  },
  {
    id: 'mem-publish-flow',
    title: 'GitHub Pages publish path for my agent systems',
    kind: 'run-summary',
    status: 'active',
    updated: '2026-09-13',
    excerpt:
      'Build with the /my-agentic-systems/ base href, copy browser output to docs, then push main.',
    content:
      'The public site is served from the docs directory in the my-agentic-systems repository. Always keep 404.html beside index.html for Angular route refreshes.',
    path: '.agent-state/cache/memory/records/my-agentic-systems-pages.yaml',
    runId: 'run-pages-publish-2026-09-13',
    sessionId: 'session-article-site',
    tags: ['github-pages', 'articles', 'publish'],
    metadata: { branch: 'main', output: 'docs' },
  },
];

export const MOCK_WORK_LOGS: WorkLog[] = [
  {
    id: 'runtime-1042-context',
    date: '2026-09-13 13:31',
    event: 'context.resolved',
    agent: 'system-engineer-agent',
    detail: 'Article app shell, controller source components, and static hosting constraints were identified.',
    status: 'complete',
    path: '.agent-state/logs/session-article-site/run-article-demo-2026-09-13/events.jsonl',
  },
  {
    id: 'runtime-1042-edit',
    date: '2026-09-13 13:54',
    event: 'source.updated',
    agent: 'system-engineer-agent',
    detail: 'Controller demo source was added with mock-backed agents, tasks, workflows, memory, logs, and messages.',
    status: 'implementing',
    path: '.agent-state/logs/session-article-site/run-article-demo-2026-09-13/events.jsonl',
  },
  {
    id: 'message-msg-9001',
    date: '2026-09-13 13:26',
    event: 'message.created',
    agent: 'controller-plane',
    detail: 'task_request sent from operator to system-engineer-agent.',
    status: 'pending',
    path: '.agent-state/messages/events-2026-09-13/msg-9001.yaml',
  },
  {
    id: 'message-msg-9003',
    date: '2026-09-13 13:44',
    event: 'ui_debug_request.sent',
    agent: 'system-engineer-agent',
    detail: 'Browser debugger was asked to inspect the article demo route after build.',
    status: 'pending',
    path: '.agent-state/messages/events-2026-09-13/msg-9003.yaml',
  },
  {
    id: 'runtime-memory-candidate',
    date: '2026-09-13 13:58',
    event: 'memory.candidate',
    agent: 'strategy-memory-analyzer',
    detail: 'Captured a possible future reminder about static demo routes and GitHub Pages refresh behavior.',
    status: 'complete',
    path: '.agent-state/cache/memory/records/my-agentic-systems-pages.yaml',
  },
  {
    id: 'runtime-1035-complete',
    date: '2026-09-12 17:22',
    event: 'task.completed',
    agent: 'agent-ui-debugger',
    detail: 'Controller UI route rendered data-backed agent cards and task columns.',
    status: 'complete',
    path: '.agent-state/logs/session-controller-check/run-ui-debug-8840/events.jsonl',
  },
  {
    id: 'runtime-1028-rework',
    date: '2026-09-11 16:14',
    event: 'feedback.failed_specificity',
    agent: 'strategy-memory-analyzer',
    detail: 'Memory proposal was marked for rework because it was too broad.',
    status: 'failed',
    path: '.agent-state/logs/session-memory-loop/run-memory-feedback-8715/events.jsonl',
  },
];

const MOCK_MESSAGES: MessageRecord[] = [
  {
    id: 'msg-9001',
    created_at: '2026-09-13T17:26:00Z',
    updated_at: '2026-09-13T17:31:28Z',
    sender: 'controller-plane',
    recipient: 'system-engineer-agent',
    type: 'task_request',
    status: 'processed',
    path: '.agent-state/messages/events-2026-09-13/msg-9001.yaml',
    folder_agent_id: 'system-engineer-agent',
    payload: {
      task_id: 'task-1042',
      title: 'Publish controller plane UI demo',
      route: '/controller-plane-ui-demo',
      acceptance: ['static mock data', 'article-nav callout', 'GitHub Pages publish'],
    },
  },
  {
    id: 'msg-9002',
    created_at: '2026-09-13T16:49:00Z',
    updated_at: '2026-09-13T16:50:11Z',
    sender: 'controller-plane',
    recipient: 'analysis-agent',
    type: 'analysis_request',
    status: 'pending',
    path: '.agent-state/messages/events-2026-09-13/msg-9002.yaml',
    folder_agent_id: 'analysis-agent',
    payload: {
      question: 'Where do failed tool calls become durable records?',
      deliverable: 'short root-cause style explanation',
    },
  },
  {
    id: 'msg-9003',
    created_at: '2026-09-13T17:44:00Z',
    updated_at: '2026-09-13T17:44:00Z',
    sender: 'system-engineer-agent',
    recipient: 'agent-ui-debugger',
    type: 'ui_debug_request',
    reply_to: 'msg-9001',
    status: 'pending',
    path: '.agent-state/messages/events-2026-09-13/msg-9003.yaml',
    folder_agent_id: 'agent-ui-debugger',
    payload: {
      url: 'http://127.0.0.1:4220/my-agentic-systems/controller-plane-ui-demo',
      wait_seconds: 1,
      full_page_screenshot: true,
    },
  },
  {
    id: 'msg-8840',
    created_at: '2026-09-12T21:10:00Z',
    updated_at: '2026-09-12T21:22:00Z',
    sender: 'system-engineer-agent',
    recipient: 'agent-ui-debugger',
    type: 'ui_debug_request',
    status: 'processed',
    path: '.agent-state/messages/events-2026-09-12/msg-8840.yaml',
    folder_agent_id: 'agent-ui-debugger',
    payload: {
      url: 'http://127.0.0.1:3101/task-thread',
      result: 'rendered task thread and agent list',
    },
  },
  {
    id: 'msg-8841',
    created_at: '2026-09-12T21:22:30Z',
    updated_at: '2026-09-12T21:22:30Z',
    sender: 'agent-ui-debugger',
    recipient: 'system-engineer-agent',
    type: 'debug_result',
    reply_to: 'msg-8840',
    status: 'processed',
    path: '.agent-state/messages/events-2026-09-12/msg-8841.yaml',
    folder_agent_id: 'system-engineer-agent',
    payload: {
      screenshot: 'artifacts/controller-task-thread.png',
      console_errors: [],
      visible_text: ['Task thread', 'Monorepo agents', '8 agents'],
    },
  },
  {
    id: 'msg-8715',
    created_at: '2026-09-11T20:05:00Z',
    updated_at: '2026-09-11T20:14:00Z',
    sender: 'controller-plane',
    recipient: 'strategy-memory-analyzer',
    type: 'feedback_received',
    status: 'failed',
    path: '.agent-state/messages/events-2026-09-11/msg-8715.yaml',
    folder_agent_id: 'strategy-memory-analyzer',
    payload: {
      feedback: 'Make diagrams render full height without internal scrolling.',
      issue: 'candidate too broad',
    },
    error: 'Memory candidate lacked a concrete validation rule.',
  },
];

export const MOCK_MESSAGING: MessagingSnapshot = {
  summary: {
    root: '.agent-state/messages',
    manifest: '.agent-state/messages/manifest.yaml',
    eventLog: '.agent-state/messages/events-2026-09-13/',
    total: MOCK_MESSAGES.length,
    tasks: MOCK_TASKS.filter((task) => Boolean(task.messageId)).length,
    unresolved: MOCK_MESSAGES.filter((message) => message.status === 'pending').length,
    activeErrors: 1,
    currentError: {
      id: 'err-memory-specificity',
      status: 'active',
      fingerprint: 'strategy-memory:proposal-too-broad',
      created_at: '2026-09-11T20:14:00Z',
      updated_at: '2026-09-11T20:14:00Z',
      occurrence_count: 1,
      error: {
        type: 'MemoryProposalNeedsRework',
        message: 'The proposed memory did not include the concrete article diagram validation rule.',
        source_message_id: 'msg-8715',
      },
    },
    byStatus: { processed: 3, pending: 2, failed: 1 },
    byType: {
      task_request: 1,
      analysis_request: 1,
      ui_debug_request: 2,
      debug_result: 1,
      feedback_received: 1,
    },
    taskStatuses: {
      implementing: 1,
      'awaiting implementation': 1,
      complete: 2,
      'need rework': 1,
    },
    agents: MOCK_AGENTS.map((agent) => agent.id),
  },
  messages: MOCK_MESSAGES,
  events: [
    {
      event_at: '2026-09-13T17:26:00Z',
      event: 'message.created',
      message_id: 'msg-9001',
      sender: 'controller-plane',
      recipient: 'system-engineer-agent',
    },
    {
      event_at: '2026-09-13T17:31:28Z',
      event: 'message.claimed',
      message_id: 'msg-9001',
      sender: 'system-engineer-agent',
      recipient: 'controller-plane',
    },
    {
      event_at: '2026-09-13T17:44:00Z',
      event: 'ui_debug_request.sent',
      message_id: 'msg-9003',
      sender: 'system-engineer-agent',
      recipient: 'agent-ui-debugger',
    },
    {
      event_at: '2026-09-12T21:22:30Z',
      event: 'debug_result.received',
      message_id: 'msg-8841',
      sender: 'agent-ui-debugger',
      recipient: 'system-engineer-agent',
    },
    {
      event_at: '2026-09-11T20:14:00Z',
      event: 'operational_error.recorded',
      message_id: 'msg-8715',
      sender: 'strategy-memory-analyzer',
      recipient: 'controller-plane',
    },
  ],
  errors: [
    {
      id: 'err-memory-specificity',
      status: 'active',
      fingerprint: 'strategy-memory:proposal-too-broad',
      created_at: '2026-09-11T20:14:00Z',
      updated_at: '2026-09-11T20:14:00Z',
      occurrence_count: 1,
      error: {
        type: 'MemoryProposalNeedsRework',
        message: 'The proposed memory did not include the concrete article diagram validation rule.',
        source_message_id: 'msg-8715',
      },
    },
  ],
};

export const MOCK_CONTROLLER_SNAPSHOT: ControllerSnapshot = {
  agents: MOCK_AGENTS,
  tasks: MOCK_TASKS,
  skills: MOCK_SKILLS,
  workflows: MOCK_WORKFLOWS,
  memory: MOCK_MEMORY,
  workLogs: MOCK_WORK_LOGS,
  messaging: MOCK_MESSAGING,
};
