export type ArticleSection = {
  heading: string;
  paragraphs: string[];
  bullets?: string[];
  diagram?: ArticleDiagram;
};

export type ArticleDiagram = {
  src: string;
  alt: string;
  size?: 'short' | 'medium' | 'tall';
};

export type Article = {
  slug: string;
  title: string;
  kicker: string;
  summary: string;
  diagram: string;
  diagramAlt: string;
  diagramSize?: 'short' | 'medium' | 'tall';
  readingTime: string;
  sections: ArticleSection[];
  example?: {
    title: string;
    code: string;
  };
};

export const ARTICLES: Article[] = [
  {
    slug: 'why-i-built-my-agent-systems',
    title: 'Building a Local Agent Control Plane Around Codex',
    kicker: 'System profile',
    readingTime: '18 min read',
    diagram: 'diagrams/personal-agent-system.html',
    diagramAlt: 'High-level view of personal engineering intent flowing into custom agents, structured workflows, memory, feedback, and better future Codex collaboration.',
    diagramSize: 'tall',
    summary:
      'A personal and practical introduction to the local Codex-powered agent system I am building: a control plane for routing work, using specialist agents, preserving evidence, accepting feedback, and improving my engineering collaboration style over time.',
    sections: [
      {
        heading: 'Why I started building this',
        paragraphs: [
          'I am building this local Codex-powered agent system in my spare time because I wanted a better working relationship with coding agents. I did not want the experience to stop at a prompt box, a terminal command, and a long answer that disappears into chat history. I wanted an environment that could route work, use specialist agents, validate results, remember useful lessons, accept feedback, and slowly become more aligned with the way I think through engineering problems.',
          'The deeper motivation is personal. Every engineer has a working style. Mine is built around understanding the system before changing it, keeping architecture boundaries visible, validating claims with real evidence, and leaving enough durable state that future work can continue from a good place. I wanted my agents to learn that style over time. Not by pretending to know me magically, but by reading structured project state, remembering verified lessons, and using feedback from completed work.',
          'When I come back to a project after several days, I do not want every session to feel like the first session again. I want the agent to know the important paths, the known validation habits, the common failure modes, the way I prefer summaries, and the difference between a quick source check and real browser evidence. I also want the agent to stay grounded: memory should help it ask better first questions, not override the current repository.',
          'That is why this system is more than a set of custom prompts. It is a local agent control plane around Codex. It treats agent work as something inspectable, reusable, and evidence-backed after the model turn is over.'
        ],
      },
      {
        heading: 'What this system is',
        paragraphs: [
          'At the center is a shared runtime that treats agent work as an observable system, not a private chat transcript. A request enters through the native Codex experience or a gateway-facing caller. The resolver chooses the right owner, normally the system engineer agent, and the workflow engine moves the work through health checks, context, planning, implementation, validation, change-impact review, and finalization.',
          'That may sound procedural, and it is. The useful part is that each step creates evidence. Runtime events are persisted. Controller tasks are visible. Message handoffs are durable. Browser debugging writes screenshots and network logs. Memory is derived from completed work rather than guessed in advance. The system can resume, inspect, rework, and learn because it leaves a trail.',
          'The diagram above was generated by the standalone agentic diagram builder that is part of the same broader effort. That builder matters because it follows the same idea: repeated interaction, feedback, and remembered preferences should produce more consistent output. In this case, it turns architecture thinking into scoped, publishable diagrams instead of one-off illustrations.'
        ],
        diagram: {
          src: 'diagrams/personal-agent-roles.html',
          alt: 'Custom agent roles arranged around one Codex collaboration loop: system engineer, planner, debugger, validator, feedback analyzer, and controller.',
          size: 'tall',
        },
      },
      {
        heading: 'The design I care about',
        paragraphs: [
          'Most agent demos optimize for a clean prompt and a dramatic answer. I care more about what happens between the prompt and the answer. That is where real engineering reliability lives: in routing, context gathering, tool use, validation, rework, logging, memory, and final artifacts.',
          'This system separates responsibilities deliberately. The native Codex CLI remains the main terminal experience. Agent identity and behavior live in agent definitions. Workflow policy lives in workflow YAML. Path ownership and controller-safe file operations live in the controller plane. The gateway stays thin and delegates execution to the runtime. Runtime events are the shared contract for live state, artifacts, metrics, summaries, and memory candidates.',
          'That boundary discipline keeps the system understandable as it grows. The UI does not become a workflow engine. The gateway does not become an orchestration layer. Memory does not outrank current source. New agents stay declarative unless deterministic code actually earns its place.',
          'The system I needed had four practical qualities: structured workflow, durable messaging, memory that improves future sessions, and a controller plane where I can see what is happening. Those qualities depend on each other. A workflow without messages is hard to coordinate. Messages without artifacts are hard to trust. Memory without feedback becomes generic. A controller without runtime boundaries becomes another hidden engine.'
        ],
        bullets: [
          'Native Codex remains the day-to-day interaction surface.',
          'Specialist agents are useful only when their ownership is clear.',
          'Runtime events and final artifacts preserve what actually happened.',
          'Memory is treated as guidance, while current source remains the authority.',
          'Validation is split into separate claims instead of one vague done state.'
        ],
      },
      {
        heading: 'Agent routing without confusion',
        paragraphs: [
          'The default owner is the system engineer agent. It is responsible for normal repository work end to end: understand the request, inspect the source, implement the change, validate it, evaluate impact, and report the result. That clear default prevents multi-agent work from turning into a crowd with no owner.',
          'Other agents have narrower jobs. A planner helps when the work needs a structured plan. An analysis agent can investigate when the job is mostly understanding. A UI debugger captures browser evidence. A strategy-memory analyzer turns useful feedback into durable guidance. The root agent is reserved for bootstrap, controller recovery, project attachment, and system-level drift.',
          'This matters because multi-agent systems become messy when every agent can be in charge. Helpers can contribute, but ownership has to stay clear. The point is not to have more agents. The point is to have better handoffs, better evidence, and less confusion about who owns the next decision.'
        ],
      },
      {
        heading: 'Workflow as real policy',
        paragraphs: [
          'The workflows are not just documentation. They are YAML execution policy. A normal feature path starts with control-plane health, gathers understanding, runs optional helpers only when they are useful, implements through the system engineer, runs deterministic validation, evaluates change impact, and finalizes.',
          'Specialized workflows exist for analysis, plan-only work, validation, error remediation, smoke checks, and implementation planning. The step catalog supports agent steps, shell checks, hooks, controller actions, message topics, nested workflows, parallel validation, and conditional helper work. That lets the system express process without hard-coding every new behavior into one large branch of code.',
          'For my style of work, this is important. I want structured output. I want a task to have visible phases. I want a final answer to be supported by artifacts. I want rework and feedback to have a path back into the run. Workflow policy gives the agents a rhythm that can be inspected and improved.'
        ],
        diagram: {
          src: 'diagrams/personal-memory-growth.html',
          alt: 'Memory growth path from completed work and feedback into future Codex context, with current source remaining the authority.',
          size: 'tall',
        },
      },
      {
        heading: 'Memory that has to earn its place',
        paragraphs: [
          'The memory layer is intentionally conservative. The goal is not to store everything. Saving everything creates noise, stale advice, and a quiet pressure to trust old context more than current code. Useful memory should earn its place by capturing hard-to-rediscover lessons: environment failures, validation commands, path boundaries, migration decisions, workflow contracts, and reusable strategy feedback.',
          'The system can derive memory candidates from completed runtime events and can also store strategy memory from feedback. That distinction matters. Event-derived memory says what happened. Strategy memory says how I want future work to be done. Together, they help future agents start with better judgment while still checking the current repository.',
          'Over time, this is what makes the system more personal. It can remember my long-term practices, my validation expectations, and my architecture preferences. It can remember that browser evidence is different from a production build, that durable task state matters, and that final summaries should be compact but traceable.',
          'The memory should make the next run better than the last one. It should not make the agent overconfident.'
        ],
      },
      {
        heading: 'Why the controller plane matters',
        paragraphs: [
          'The controller is the operator surface. The Angular UI and API read agents, skills, workflows, task records, memory records, work logs, and messaging records from the repository. Creating a task writes a durable request, links it to a task record, and launches work through the shared runtime only when the launch path is explicit.',
          'This gives me a place to inspect the system instead of relying only on terminal scrollback. I can see what is queued, what ran, which messages exist, which artifacts were produced, which memory records are active, and which operational error needs attention. The controller is not supposed to become a second runtime. Its job is to make work visible and controllable.',
          'The same idea applies to the MQ plane and internal messaging. Durable messages turn handoffs into inspectable records. A caller can see what was asked, who handled it, what evidence was produced, and what happened next. That is the difference between an agent doing something privately and a system showing its work.'
        ],
      },
      {
        heading: 'The feature map',
        paragraphs: [
          'The current system brings several pieces together: native Codex passthrough, deterministic routing, declarative agents, YAML workflows, optional helper agents, runtime event streaming, final artifacts, bounded memory retrieval, strategy feedback, a message bus, an MQ control plane, a controller UI, browser debugging, logging, active error tracking, offline tests, and a standalone diagram/article builder.',
          'That list is long, but the idea behind it is simple. Agent engineering is not only asking a model to write code. It is building the surrounding system that lets model work become dependable: routing, context, tools, feedback, evidence, memory, validation, and recovery.',
          'This repository is my attempt to make that surrounding system concrete. It is local-first, inspectable, and deliberately practical in the places where reliability matters. The agent can think, but the system has to remember what happened, show its work, and make the next run better than the last one.'
        ],
      },
      {
        heading: 'What this article series explains',
        paragraphs: [
          'The rest of this series explains the system from the inside out. It starts with messaging because messages are the coordination layer. It moves into UI debugging because browser evidence is a good example of tool use through messages. Then it covers collaboration patterns, memory, feedback, logging, controller-plane design, and future memory integrations.',
          'My goal is to make the system easy to understand even if the implementation has many parts. Each article tries to answer the same practical question: what problem does this layer solve, and why does it make Codex collaboration better?'
        ],
      },
    ],
  },
  {
    slug: 'aws-memory-architecture-plan',
    title: 'AWS Architecture Design Plan for My Codex Agent Memory System',
    kicker: 'Memory expansion plan',
    readingTime: '15 min read',
    diagram: 'diagrams/aws-memory-architecture.html',
    diagramAlt: 'AWS architecture for Codex agent memory using API Gateway, Lambda authorizer, memory save and get Lambdas, S3, DynamoDB, Bedrock, and a vector index.',
    diagramSize: 'tall',
    summary:
      'A practical AWS plan for moving my local Codex agent memory system toward a durable cloud-backed memory layer without losing the simple rules that make the local system trustworthy.',
    sections: [
      {
        heading: 'The architecture I want to build toward',
        paragraphs: [
          'The memory system in my Codex agent setup should eventually have two lives. Locally, it should stay fast, inspectable, and close to the repository. In AWS, it should become durable enough to support long-running work across machines, sessions, and future agent tools. The cloud layer should not replace the local runtime. It should give the runtime a reliable place to save memory, fetch memory, and run lightweight processing when that is the cheaper and cleaner path.',
          'The high-level AWS design starts with API Gateway. I want clear endpoints for different purposes instead of one vague memory API. `/agent/auth` handles authentication. `/agent/memory/save` receives reviewed memory candidates and stores them. `/agent/memory/get` returns scoped context for a new agent run. Each endpoint sits behind a Lambda authorizer so requests are checked before the memory Lambdas do any real work.',
          'Behind those endpoints, Lambda functions keep the processing small and focused. One function validates authentication. One function saves memory records. One function retrieves memory context. Supporting functions can classify memory, redact sensitive values, create embeddings, or call Bedrock for small summarization and labeling tasks. This keeps the architecture modular enough that I can improve one step without rewriting the whole memory layer.'
        ],
      },
      {
        heading: 'Why this belongs outside the main runtime',
        paragraphs: [
          'The local runtime should stay responsible for agent execution, workflow steps, events, final artifacts, and prompt assembly. AWS should handle durable storage and optional cloud processing. That boundary is important. If the cloud side starts making workflow decisions, the agent system becomes harder to reason about. A local run should still be able to say what happened, what memory was used, and which files or commands proved the current truth.',
          'The cloud memory service should behave like a reliable assistant to the runtime. It receives structured records, stores them with provenance, and returns small context blocks. It should not silently push giant summaries into every prompt. It should not override current source. It should not turn every old note into a fact. Good memory helps the agent start with better context, then the agent still verifies the repository in front of it.',
          'This is why the API is intentionally narrow. A save endpoint is for durable memory writes. A get endpoint is for retrieval. Authentication is its own concern. Model calls are a support step, not the owner of memory truth.'
        ],
      },
      {
        heading: 'The save path',
        paragraphs: [
          'A memory save should begin only after the agent run has produced evidence. The local system already has the right raw material: runtime events, changed files, final artifacts, validation output, and operator feedback. The cloud save path should receive a memory candidate that has already been shaped into a useful record: kind, scope, source, confidence, status, and content.',
          'Before the record reaches durable storage, the save Lambda should run a small set of gates. It should check authentication context, validate the schema, reject unexpected paths, scan for secrets, classify the memory kind, and decide whether the record is a candidate or an accepted active memory. A save endpoint that stores everything immediately will become noisy very quickly.',
          'S3 is a good place for raw evidence and larger artifacts. DynamoDB is a good place for the memory index, metadata, status, source pointers, confidence, privacy, and retrieval filters. A vector index is the better home for semantic search once the system needs it. DynamoDB can keep embedding text, embedding model metadata, and links to vector entries, but I would not make it the main semantic search engine unless the retrieval needs are still very small.'
        ],
        diagram: {
          src: 'diagrams/aws-memory-save-flow.html',
          alt: 'Memory save flow from completed local Codex work through candidate review, redaction, classification, and durable AWS storage.',
          size: 'tall',
        },
      },
      {
        heading: 'The get path',
        paragraphs: [
          'The memory get path should start with scope. A request should say which repository, project, service, agent, task type, and prompt it is working with. Without scope, retrieval becomes a pile of related-looking notes. With scope, the service can return memory that is useful for the current task instead of memory that merely sounds familiar.',
          'The retrieval Lambda can query DynamoDB for exact filters first: repo, project, service, memory kind, status, privacy, and validity. Then it can ask the vector index for semantic matches when exact wording is not enough. The result should be merged, reranked, and trimmed before it returns to the local agent. The response should be small enough to fit comfortably into a prompt and clear enough that the agent knows why each memory was included.',
          'For example, if I ask Codex to work on the controller UI, the memory service should prefer active controller-specific records, known validation commands, recent failures, and durable strategy preferences. It should not return a random old thought about a different project just because some words overlap.'
        ],
        diagram: {
          src: 'diagrams/aws-memory-get-flow.html',
          alt: 'Memory retrieval flow from a new agent request through scoped filters, vector search, evidence lookup, reranking, and bounded prompt injection.',
          size: 'tall',
        },
      },
      {
        heading: 'Where Bedrock fits',
        paragraphs: [
          'Bedrock should be used where it reduces waste. Some memory tasks do not need the full coding agent context. Classifying a memory candidate, producing a short title, summarizing a final artifact, or creating an embedding request can be handled by a smaller model path. That can reduce token consumption in the main Codex session and keep the expensive reasoning budget focused on actual engineering work.',
          'The useful rule is simple: use Bedrock for lightweight memory processing, not for replacing the agent runtime. The runtime owns the engineering loop. Bedrock can help label, compress, summarize, embed, and occasionally rerank memory records. If a task needs deep repository reasoning, current file inspection, and code edits, it belongs back in the normal Codex flow.',
          'This also gives the system a clean cost story. The memory layer can process small records in small calls. The agent session receives a compact context block instead of doing the same classification and summarization work every time.'
        ],
      },
      {
        heading: 'Security and data boundaries',
        paragraphs: [
          'Authentication cannot be decorative here. Memory may contain project paths, technical decisions, failure details, and working preferences. API Gateway should use the Lambda authorizer across the memory routes. The authorizer can validate the caller, attach identity context, and allow or deny the request before the memory function runs.',
          'The save Lambda should redact secrets before anything is written to S3, DynamoDB, or a vector index. The get Lambda should filter by privacy, project, and authorization context. S3 buckets should use encryption, versioning where useful, and lifecycle policies for artifacts that do not need to live forever. DynamoDB records should keep enough provenance to explain why a memory exists and enough status to stop stale memory from being injected.',
          'The most important security habit is not a single AWS service. It is refusing to treat memory as harmless text. Memory becomes part of future reasoning, so it needs the same care as any other project artifact.'
        ],
      },
      {
        heading: 'What I would build first',
        paragraphs: [
          'I would start small. First, implement `/agent/memory/save` for accepted memory records only, with schema validation, redaction, DynamoDB metadata, and S3 evidence pointers. Then implement `/agent/memory/get` with exact scoped retrieval from DynamoDB. Only after that path proves useful would I add embeddings and a vector index.',
          'That order matters because it keeps the first version understandable. If local memory is messy, vector search will only make the mess look smarter. The first goal is clean records. The second goal is scoped retrieval. The third goal is hybrid search. The fourth goal is feedback metrics that prove the memory is actually helping.',
          'The AWS architecture should make my Codex agent system more durable, not more mysterious. If a future agent cannot explain which memory came back, why it came back, and where it came from, the architecture is not finished.'
        ],
        bullets: [
          'Keep local events and source files as the strongest evidence.',
          'Use API Gateway routes that describe the operation clearly.',
          'Attach a Lambda authorizer to memory endpoints before processing.',
          'Use S3 for larger evidence and DynamoDB for indexed memory metadata.',
          'Add vector retrieval only after typed memory records are reliable.',
          'Use Bedrock for small memory tasks that should not spend the main agent budget.'
        ],
      },
      {
        heading: 'Source notes',
        paragraphs: [
          'This plan follows AWS patterns for API Gateway with Lambda authorizers, Lambda proxy style request handling, durable S3 object storage, Bedrock model invocation through `Converse` or `InvokeModel`, and Bedrock Knowledge Bases using vector stores such as OpenSearch Serverless. I would still verify service limits, region support, IAM policy details, and cost before turning this into production infrastructure.'
        ],
      },
    ],
  },
  {
    slug: 'memory-expansion-roadmap',
    title: 'Memory Expansion Roadmap for My Codex Agent System',
    kicker: 'Memory expansion plan',
    readingTime: '16 min read',
    diagram: 'diagrams/memory-expansion-roadmap.html',
    diagramAlt: 'Roadmap from hardened local memory to project-aware scope, consolidation, hybrid retrieval, and feedback metrics.',
    diagramSize: 'tall',
    summary:
      'A detailed but practical plan for growing agent memory from local event-derived notes into typed, scoped, reviewed, and measured recall that improves future Codex work.',
    sections: [
      {
        heading: 'The memory problem I am solving',
        paragraphs: [
          'My agent system should get better the more it works with my projects. That does not mean it should remember everything. It means it should remember the right things: project entry points, validation commands, architecture boundaries, recurring failures, user preferences, and decisions that are hard to rediscover later.',
          'The memory expansion plan starts from a grounded rule: source files, tests, runtime events, ADRs, and project docs are stronger than generated summaries. Memory is guidance. It helps the agent decide where to look first, what to be careful about, and which past lesson might matter. It should never become a shortcut around current evidence.',
          'The goal is a system where future Codex sessions feel less cold. The agent should know the shape of the project, understand past mistakes, and use my working preferences without needing me to repeat them every time.'
        ],
      },
      {
        heading: 'Phase 1: harden local memory',
        paragraphs: [
          'The first phase is local and disciplined. Each memory record should have a schema version, kind, scope, confidence, status, source events, creation time, update time, tags, and provenance. That metadata is not ceremony. It is how the system keeps memory searchable, reviewable, and safe to inject into future prompts.',
          'Candidate storage and accepted memory storage should be separate. A completed run can produce candidates, but only high-signal candidates should become active memory. A failure that will matter again is worth keeping. A generic summary that says the agent changed some files is usually not. The promotion policy is where the system learns restraint.',
          'This phase also needs tests. Retrieval budgets, stale records, duplicates, path containment, and redaction should be tested before the system gets more ambitious. If memory cannot behave locally, adding AWS or vector search will only make the failure harder to see.'
        ],
        diagram: {
          src: 'diagrams/memory-types-policy.html',
          alt: 'Typed memory policy showing project profiles, architecture facts, decisions, failures, command results, preferences, integration facts, security constraints, and retrieval feedback.',
          size: 'tall',
        },
      },
      {
        heading: 'The memory types',
        paragraphs: [
          'The plan should use explicit memory kinds. A `project-profile` explains what a project is, how it runs, and how it is validated. An `architecture-fact` records stable boundaries. A `decision` captures rationale and status. A `failure-pattern` records an error signature, root cause, and verified fix. A `command-result` saves important environment behavior.',
          'Other kinds serve different jobs. A `user-preference` stores durable working style that is not already in project instructions. A `project-glossary` maps local names and acronyms. A `dependency-fact` records version constraints. An `integration-fact` stores external API or auth details with review dates. A `security-constraint` protects secrets and permission boundaries. An `open-question` keeps unresolved assumptions from becoming facts. `retrieval-feedback` records whether memory actually helped.',
          'Putting these into one generic note bucket would be easier at first and worse later. Different memories deserve different rules for creation, expiry, review, and retrieval.'
        ],
      },
      {
        heading: 'Phase 2: project-aware memory',
        paragraphs: [
          'The next phase is scope. A monorepo can hold many systems, and agent memory should not treat them all as one flat pile. Before serious work starts inside a project, the project should have a small scaffold: `AGENTS.md`, `ARCHITECTURE.md`, `code-map.yaml`, `project.yaml`, and `README.md`.',
          '`project.yaml` should declare project id, stack, default agent, validation commands, deployment mode, and memory namespace. That gives the resolver a clean way to retrieve project-specific memory before work begins. It also gives future agents a predictable place to look before scanning half the repository.',
          'This is where memory becomes useful without becoming noisy. A controller UI task should pull controller UI facts. A runtime workflow task should pull workflow facts. A diagram builder article should pull builder facts. Good scope keeps the agent focused.'
        ],
      },
      {
        heading: 'Phase 3: consolidation',
        paragraphs: [
          'Raw run summaries should not pile up forever. A consolidation command should merge repeated failure summaries into one stronger `failure-pattern`, promote repeated architecture facts into `architecture-fact`, archive summaries that are fully represented by better records, and mark contradicted records as superseded.',
          'This should be a deterministic command, not a hidden scheduler at the beginning. A command is easier to test, easier to run on demand, and easier to explain. The system can add automation later, once there is a real operational need.',
          'Consolidation is also where project docs can improve. If a memory fact has been verified from source inspection, the system can propose updates to `ARCHITECTURE.md` or `code-map.yaml`. But that should happen only when the source backs it up. Generated memory should not rewrite project truth by itself.'
        ],
      },
      {
        heading: 'Phase 4: hybrid retrieval',
        paragraphs: [
          'Local lexical retrieval is a strong first version because exact matches matter. File paths, command names, error strings, agent ids, workflow ids, and API routes are often the best clues. But over time, exact words will not be enough. A past lesson about approval before task launch may be relevant even when the new request uses different language.',
          'That is where hybrid retrieval becomes useful. The system should determine scope, retrieve exact matches, retrieve semantic matches from a vector index, filter by kind and status, merge scores, rerank by confidence and source quality, and compress the result to a strict token budget. The output should be a small memory block, not a bag of notes.',
          'For a production-grade AWS path, OpenSearch Serverless is a sensible first vector search target because it supports vector search and full-text search with filters. Bedrock Knowledge Bases can also help when the system grows into a managed RAG path. The durable source of truth should still be the memory records themselves.'
        ],
      },
      {
        heading: 'Phase 5: performance feedback',
        paragraphs: [
          'The memory system should measure whether it helps. It should record how many memories were retrieved, how many tokens were injected, which memory ids were used, whether the final work referenced them, whether validation succeeded, and whether any retrieved memory was stale or contradicted.',
          'Those metrics give the system a way to tune itself. Maybe some memory kinds are too noisy. Maybe old command results should decay faster. Maybe vector search is useful for architecture work but not for quick syntax fixes. Without measurement, memory can feel impressive while quietly making the agent worse.',
          'A good feedback loop should be honest enough to say when memory was ignored. That is still useful. It means the retrieval policy can learn what not to bring back next time.'
        ],
        diagram: {
          src: 'diagrams/memory-feedback-metrics.html',
          alt: 'Memory feedback and metrics loop showing retrieved ids, injected tokens, validation result, usefulness labels, and retrieval tuning.',
          size: 'tall',
        },
      },
      {
        heading: 'What better memory should feel like',
        paragraphs: [
          'Better memory should feel calm. The agent should not sound like it has read a thousand private notes. It should simply start in a better place. It should know the likely project, the expected validation path, the common mistakes, and the preferences that apply to the work.',
          'The final behavior I want is practical. When I ask for a change, Codex should retrieve a few relevant records, inspect the current source, decide whether the memory still applies, and then work. If a memory is stale, the agent should say so and the system should mark it for review. If a memory helps, the run should record that too.',
          'That is the kind of memory system worth building: typed, scoped, reviewed, measured, and humble enough to let the current repository win.'
        ],
      },
    ],
    example: {
      title: 'Example memory record shape',
      code: `{
  "schema_version": 1,
  "id": "controller-ui-validation-browser-evidence",
  "kind": "user-preference",
  "scope": {
    "repo": "agent-monorepo",
    "project": "applications/controller-ui",
    "service": "frontend"
  },
  "source": {
    "run_id": "run-2026-09-13",
    "files": ["applications/controller-ui/src/app"]
  },
  "content": "For UI changes, verify rendered browser behavior and report screenshot, console, and network evidence separately.",
  "confidence": 0.86,
  "privacy": "normal",
  "status": "active",
  "tags": ["ui", "validation", "browser-evidence"]
}`,
    },
  },
  {
    slug: 'core-diagram-builder-approach',
    title: 'The Core Diagram Builder Behind My Agent Articles',
    kicker: 'Diagram builder',
    readingTime: '12 min read',
    diagram: 'diagrams/diagram-builder-core.html',
    diagramAlt: 'Core builder flow from architecture idea to declarative YAML, reusable component libraries, validation, static HTML, and article iframe.',
    diagramSize: 'tall',
    summary:
      'A focused look at the standalone diagram builder core: how YAML, reusable libraries, validation, and static HTML output make architecture diagrams repeatable for agent-system articles.',
    sections: [
      {
        heading: 'Why I wanted a builder instead of one-off drawings',
        paragraphs: [
          'When I write about an agent system, the diagram is not decoration. It is part of the explanation. A good diagram should show ownership, flow, handoff, storage, feedback, and boundaries. If every diagram is manually drawn from scratch, the style drifts and small updates become annoying.',
          'The core diagram builder solves that by turning declarative YAML into static HTML diagrams. I describe the structure in a small file. The builder loads reusable component libraries, validates the requested shape, and renders a transparent-background diagram that can sit inside an article page.',
          'For now, this article is only about the core builder under `standalone-systems/agentic-diagram-and-article-builder/builder-libs`. I am intentionally leaving the UI and service layers out of scope. The important idea is the authoring model: diagrams should be repeatable, inspectable, and easy for an agent to produce consistently.'
        ],
      },
      {
        heading: 'The builder model',
        paragraphs: [
          'The input document is simple. It has a title, an optional subtitle, and a `diagrams` list. Each diagram can be a flow, tree, event bus, component, component stack, or component gallery. That gives enough variety for articles without turning the builder into a full drawing application.',
          '`diagram_builder.py` owns the CLI entry point. It reads YAML, loads component catalogs, validates fields, renders HTML, and writes the output file. The generated HTML links to `assets/styles.css`, which keeps the diagram visual language consistent across pages.',
          'This matters for agent-written articles. The agent can produce a small YAML file instead of trying to hand-code every connector. The result is easier to review because the source says what the diagram means.'
        ],
        diagram: {
          src: 'diagrams/diagram-builder-libraries.html',
          alt: 'Diagram builder library layers showing core components, composite components, text composites, pattern recipes, and article diagram YAML.',
          size: 'tall',
        },
      },
      {
        heading: 'The reusable library approach',
        paragraphs: [
          'The library split keeps the builder practical. `core-components.yaml` defines small pieces such as labels, arrows, tree labels, event-bus nodes, and plain rectangles. `composite-components.yaml` defines larger fan-in and fan-out geometry such as two-node and three-node components. `text-composite-components.yaml` gives conceptual variants. `pattern-recipes.yaml` gives copyable starting points.',
          'That design is useful because most architecture articles repeat a small set of shapes. A user request enters a system. It branches into handlers. It lands in storage. It comes back as context. The builder should make those common forms easy without hiding the meaning of the diagram.',
          'The current article diagrams use `component_stack` heavily because it is a good fit for architecture writing. It lets me stack a source, gateway, processing layer, storage layer, and output layer with consistent connector geometry.'
        ],
      },
      {
        heading: 'Validation is part of the writing workflow',
        paragraphs: [
          'A diagram builder should fail early when the YAML asks for an impossible shape. Three-node components should receive three nodes. Two-node components should receive two. Required fields should be present. Unknown component names should be rejected. These checks make the tool more useful for agents because mistakes are caught before publishing.',
          'Validation also keeps the visual language stable. If a compound component already owns its connector geometry, the neighboring element should usually be `node-only`. That kind of rule sounds small, but it prevents duplicated arrows and crowded diagrams.',
          'The best part is that the article source stays readable. I can review the YAML and understand the diagram without opening a drawing tool.'
        ],
      },
      {
        heading: 'How it fits my article site',
        paragraphs: [
          'The article site embeds each generated diagram as a static HTML iframe. The diagram page has a transparent background, while the article frame supplies the border and caption. That gives each article a consistent reading experience and lets the builder remain independent from Angular.',
          'For GitHub Pages, static HTML output is a good fit. There is no runtime service to start and no API needed just to render a diagram. The build copies the diagram assets into the published `docs/` folder with the rest of the Angular app.',
          'The key publishing requirement is height. Architecture diagrams should render completely without inner scrolling, including on tablet and mobile. That is why the article frame gives tall diagrams more vertical room and why the diagrams themselves stay compact.'
        ],
      },
      {
        heading: 'Future improvement plan',
        paragraphs: [
          'The next improvements should make authoring and publishing safer. I would add a diagram linter that explains bad component combinations in plain language. I would add preview size checks for desktop, tablet, and mobile article frames. I would add image export for places where static PNG is safer than iframe HTML.',
          'I would also like recipe suggestions. If an agent is writing about message passing, memory retrieval, or controller-plane flow, it should be able to pick a known pattern and fill in the labels. That would make diagrams faster while keeping them consistent.',
          'Eventually, the builder can become part of the agent memory loop. If I repeatedly correct diagram style, the system should remember those preferences: keep labels short, avoid oversized stacks, use full-height frames, and make the article diagram explain a real system boundary.'
        ],
        diagram: {
          src: 'diagrams/diagram-builder-roadmap.html',
          alt: 'Diagram builder future plan showing schema validation, recipe catalog, responsive frames, linting, preview sizes, export images, and publish verification.',
          size: 'tall',
        },
      },
      {
        heading: 'The principle underneath it',
        paragraphs: [
          'The builder follows the same principle as the agent system itself. Durable structure beats one-off output. A diagram should have source. A workflow should have events. A memory should have provenance. A controller task should have a record.',
          'That is why the diagram builder belongs in this article series. It is not just a utility for making pictures. It is another example of making agent-assisted work visible, repeatable, and easier to improve over time.'
        ],
      },
    ],
  },
  {
    slug: 'internal-messaging',
    title: 'Inside the Agent Internal Messaging System',
    kicker: 'Messaging foundation',
    readingTime: '16 min read',
    diagram: 'diagrams/internal-messaging.html',
    diagramAlt: 'Data flow from user request to controller, message records, runtime, replies, task records, and operational errors.',
    diagramSize: 'tall',
    summary:
      'A practical tour of how agents coordinate through durable messages, why compact replies matter, and how the same message shape supports tool calls, task creation, UI debugging, error handling, and recovery.',
    sections: [
      {
        heading: 'Why messages are the center of the system',
        paragraphs: [
          'The most important design choice in this agent system is that agents do not have to behave like a pile of direct function calls. They can communicate by writing durable messages. That sounds simple, but it changes the shape of the whole platform. A message gives the sender a clear contract, gives the receiver a bounded job, and gives the operator a trail that can be inspected after the process that created it has already exited.',
          'There are two layers worth separating. The current cross-component control path is the FastAPI MQ server, which accepts topics such as workflow execution, file actions, system errors, and todo requests, then persists state transitions as YAML under `.agent-state/messages/`. Beside it, the file-backed agent bus under `.agent-state/agents-messaging/` remains the transparent agent-to-agent work surface for controller tasks, debugger requests, replies, task records, active errors, and debug artifacts. The site you are reading about leans on both ideas: command topics for system coordination, and rich durable agent messages for work that needs human visibility.',
          'The reason this is effective is not novelty. It is the discipline of making every handoff explicit. A message records who asked, who should act, what type of work is requested, what payload is needed, and whether it is a reply to an earlier message. Once that record exists, the system can queue it, display it, process it, retry it, mark it failed, or archive it without losing the thread.'
        ],
      },
      {
        heading: 'The shape of one message',
        paragraphs: [
          'A normal agent message is deliberately small. It carries `id`, `created_at`, `sender`, `recipient`, `type`, `payload`, and optional `reply_to`. That is enough to represent a task request, a UI debugger request, a tool request, an error alert, a cleanup request, or a result. The payload can be specific to the message type while the lifecycle stays common.',
          'The bus writes the pending file into the recipient inbox and also creates an indexed record under `records/messages/`. That second copy is important for dashboards. The controller UI should not scrape inbox folders and infer meaning from filenames. It asks the backend for a structured messaging snapshot, and the backend reads the durable records, events, tasks, and errors into one view.',
          'When a handler accepts the message, the file moves from `inbox/<agent-id>/` to `processed/<agent-id>/`. If the handler cannot run it, the file moves to `failed/<agent-id>/` and receives a sibling error note. Either way, the message record changes status and a lifecycle event is appended to `records/events.jsonl`. The visible audit trail is not an afterthought; it is part of the message write.'
        ],
        diagram: {
          src: 'diagrams/internal-message-lifecycle.html',
          alt: 'Lifecycle detail showing a message moving from inbox to processed or failed records, with reply threading and event logging.',
          size: 'tall',
        },
      },
      {
        heading: 'Task creation as a message flow',
        paragraphs: [
          'Controller-created work is a clean example. The user creates a task in the controller. The backend writes a `task_request` message addressed to the selected agent, writes a task record under `records/tasks/`, and marks the task as awaiting implementation. That waiting state is intentional. It keeps the controller honest: task creation and task execution are different moments, and the user explicitly approves the launch.',
          'After approval, the task runner reads the queued message, marks the task as implementing, and delegates the actual work to the normal runtime gateway. The runtime still owns agent selection, workflow execution, events, finalization, and memory candidates. When the run completes, the task runner updates the task to complete or need rework and sends a `task_request.result` reply. That reply is a normal message with `reply_to` pointing back to the original task request.',
          'This pattern is what lets the controller show a task thread instead of a vague job spinner. The operator can inspect the original request, the launch event, the runtime result, and any follow-up reply. If a task needs rework, that status belongs in the record rather than in someone’s memory of a terminal log.'
        ],
      },
      {
        heading: 'Tool calls without hidden side effects',
        paragraphs: [
          'Message passing also makes tool use easier to reason about. An agent can request a deterministic tool by message instead of embedding a large tool transcript inside its own conversation. The UI debugger is the clearest case, but the same style works for cleanup, health checks, log analysis, and future tools that produce large evidence. The message says what is needed. The handler runs the tool. The reply returns the compact result and paths to the full artifacts.',
          'That separation protects model context. A screenshot, browser console dump, or long network log does not belong inline in every message. The durable artifact belongs on disk, and the reply should say where it is, whether the run succeeded, and which failures matter. Agents get the information needed to decide the next step without dragging a whole debug session through every prompt.',
          'The same idea applies to file and workflow actions in the MQ server. Cross-component callers can use topics such as `read-file`, `write-file`, `update-file`, `run-workflow`, and `system-error`. The MQ server persists pending, processing, and processed transitions so the caller can inspect what happened even when the action is deterministic and quick.'
        ],
      },
      {
        heading: 'Error handling as operational state',
        paragraphs: [
          'Error handling is another place where message-first design pays off. An error should not be a line that scrolls away. When the runtime emits an error event, or when the log analyzer sees a fresh `ERROR` line, the exact error object can be recorded through the message bus. The bus writes or updates `current-error.json`, sends an `error.detected` message, and appends the error lifecycle event.',
          'That gives the system one active operational error pointer. If a different error appears while one is already active, the older record is archived as superseded. If the current error is fixed and confirmed, it is archived as fixed. This is more useful than dumping every error into permanent memory. Active error state answers: what needs attention now? Long-term memory answers: what lesson should future agents remember?',
          'The distinction keeps the agent from over-learning from temporary incidents. A failed port bind, a malformed record, or a browser startup issue may need immediate visibility, but it should become memory only if it teaches a reusable project lesson.'
        ],
      },
      {
        heading: 'Why the system feels efficient',
        paragraphs: [
          'The efficiency comes from boring guarantees. Every message has a recipient. Every handled message has a status. Every large artifact has a path. Every reply can point back to its request. The controller reads structured snapshots rather than asking the browser to parse raw files. The runtime owns execution rather than letting the UI become a second workflow engine.',
          'Because messages are durable, agents can collaborate asynchronously. A planner can create tasks. A debugger can inspect a URL. A log analyzer can report an operational error. A system engineer can read the current inbox count before starting a step. None of those participants needs a private, invisible side channel.',
          'That is the real value of the internal messaging system: it makes agent work inspectable at the same level where it is coordinated. The message is not just transport. It is the unit of accountability.'
        ],
        bullets: [
          'Use compact payloads for requests and compact summaries for replies.',
          'Put large evidence in artifacts and return paths, not blobs of text.',
          'Treat active errors as operational state until a verified fix exists.',
          'Keep runtime execution in the runtime and controller visibility in the controller.',
          'Prefer explicit `reply_to` threads over disconnected status comments.'
        ],
      },
      {
        heading: 'How agents should use messages in practice',
        paragraphs: [
          'The practical rule for an agent is simple: send a message when another participant owns the work, when the result should be durable, or when the output is too large to live comfortably inside the current prompt. A browser inspection, a controller task, a cleanup request, a log-analysis request, and an operational error are all good message candidates.',
          'The sender should describe the requested outcome rather than leaking its internal reasoning. A debugger request should say which URL to inspect, which viewport matters, and what evidence is needed. A task request should say what the operator wants done, what boundaries matter, and which result shape is expected. The receiver can then do focused work and return a compact answer.',
          'The receiver should reply with the result, status, artifact paths, and the next useful decision. If the work failed, the failure should be clear enough that another agent can continue without guessing. If the work succeeded, the reply should avoid dumping unnecessary evidence into the thread. The message bus becomes effective when both sides respect that compact contract.',
          'This is also where task creation, tool calling, error handling, and agent collaboration meet. They look like different features in the UI, but they are all variations of the same durable exchange: request, handle, record, reply, and inspect.'
        ],
      },
    ],
    example: {
      title: 'Example message event',
      code: `{
  "id": "8f4a0d0c8f7a4f3fa5e0b1c88d3a72fb",
  "created_at": "2026-09-13T06:20:18Z",
  "sender": "controller-api",
  "recipient": "agent-ui-debugger",
  "type": "ui_debug_request",
  "reply_to": null,
  "payload": {
    "url": "http://localhost:4220/articles/internal-messaging",
    "request_id": "article-site-visual-check",
    "wait_seconds": 1,
    "viewport_width": 1440,
    "viewport_height": 1100,
    "full_page_screenshot": true
  }
}`,
    },
  },
  {
    slug: 'ui-debugger-message-passing',
    title: 'Debugging the UI by Sending a Message',
    kicker: 'Browser evidence',
    readingTime: '12 min read',
    diagram: 'diagrams/ui-debugger.html',
    diagramAlt: 'Message path from an agent or controller to the UI debugger, Selenium capture, artifacts, and compact reply.',
    diagramSize: 'tall',
    summary:
      'The UI debugger works best when it behaves like an agent-facing service: request by message, inspect through Selenium, store artifacts, and reply with only the useful evidence.',
    sections: [
      {
        heading: 'The debugger is a participant, not a side errand',
        paragraphs: [
          'A UI bug is rarely proven by a successful build. Builds tell us the code can compile. They do not tell us whether a page is blank, whether a button is covered, whether a route crashes after navigation, or whether a data fetch failed in the browser. The UI debugger exists to close that gap with real browser evidence.',
          'In this system, agents can call the debugger through the same message fabric used for other work. A requester sends a `ui_debug_request` to `agent-ui-debugger`. The message payload stays small: URL, request id, viewport, wait time, full-page preference, and any notes. The hub receives it, invokes the Selenium runner, writes artifacts, then sends a `ui_debug_request.result` reply back to the requester.',
          'That message path matters because it turns debugging into a repeatable workflow. The agent that changed the UI does not need to invent a one-off browser script. It asks the debugger for evidence, reads the result, and decides what to fix next.'
        ],
      },
      {
        heading: 'What the debugger captures',
        paragraphs: [
          'The runner opens the supplied URL in headless Chrome with browser and performance logging enabled. It waits for the document to load, captures a screenshot, records console output, filters Chrome DevTools network events, and writes a manifest. The important part is the filter. The system does not want every image, font, and successful request. It wants actionable failed XHR, fetch, document, and network-loading failures.',
          'The artifacts are stored under `.agent-state/agents-messaging/debug-sessions/<request-id>/`. The reply includes paths to `manifest.json`, screenshot output, console logs, and network error records. It also includes counts and first errors so the receiving agent can understand the situation without reading several large files every time.',
          'This gives the operator and the agent the same evidence. A human can open the screenshot. An agent can parse the compact reply. The controller can show the message thread and artifact paths. The browser session becomes part of the durable task story.'
        ],
        diagram: {
          src: 'diagrams/ui-debugger-artifacts.html',
          alt: 'UI debugger artifact set showing screenshot, console records, network failures, manifest, and compact reply.',
          size: 'tall',
        },
      },
      {
        heading: 'Why message passing is the right call surface',
        paragraphs: [
          'The debugger launches a browser, and browser automation can fail for environmental reasons. Chrome might not start. A page may not respond. A local server may not be running. The message bus gives those failures a place to land. The message can be marked failed, the reply can include the exception, and the controller can keep the failure visible.',
          'Directly invoking the debugger from inside every agent would make each workflow responsible for the same setup, failure handling, artifact naming, and result compaction. The message-handler boundary centralizes that logic. Agents learn one request shape and one result shape.',
          'The pattern also encourages better UI work habits. After changing a route, an agent can request a desktop and mobile check. The debugger returns screenshot and network evidence. If the result shows overlap, console errors, or failed API calls, the agent can patch the component and send another request. The final claim is then backed by observed browser behavior instead of confidence.'
        ],
      },
      {
        heading: 'A useful debugging strategy',
        paragraphs: [
          'The best strategy is to ask narrow questions. Instead of “check the app,” request the route that changed, the viewport that matters, and the condition that might break. For an article site, that might mean checking a long article page at desktop width and a route refresh at the GitHub Pages base path. For a controller workflow, it might mean checking the messaging portal after creating a debugger request.',
          'The result should guide action. A screenshot answers layout. Console logs answer runtime errors. Network failures answer whether the UI actually reached the backend. The manifest ties those files to the request. When an agent reports that a UI is ready, it should say which evidence was captured and which failures, if any, remain.',
          'This is how the debugger becomes more than a test utility. It becomes a shared inspection service for agents and operators.'
        ],
      },
      {
        heading: 'How debugger evidence changes the agent conversation',
        paragraphs: [
          'A good debugger result changes the next agent turn from opinion to diagnosis. Instead of saying the page should render, the agent can say the page loaded, the screenshot was captured, the console was clean, and no actionable XHR or fetch failures were found. If the evidence is bad, the agent can point to the exact browser error or failed request that needs attention.',
          'This is especially useful for work that passes static checks but fails in the browser. A route can compile and still render blank because data is missing. A component can build and still overlap on a narrower viewport. A published GitHub Pages app can work locally and fail after base-href routing. Browser evidence catches those differences.',
          'The message-passing strategy also makes debugger work repeatable. An agent can request the same URL after each fix and compare the next result. The final article, feature, or controller screen is then backed by an evidence trail rather than a single optimistic run.'
        ],
      },
    ],
  },
  {
    slug: 'agentic-collaboration-patterns',
    title: 'Agentic Collaboration Patterns That Stay Understandable',
    kicker: 'System design',
    readingTime: '13 min read',
    diagram: 'diagrams/collaboration.html',
    diagramAlt: 'Planner, system engineer, debugger, validator, memory, and operator feedback connected through shared runtime events.',
    diagramSize: 'tall',
    summary:
      'Good agent collaboration is not about having more agents. It is about giving each participant a clean boundary, a useful handoff, and a durable record of what happened.',
    sections: [
      {
        heading: 'Collaboration starts with ownership',
        paragraphs: [
          'The system works because the default owner is clear. Normal repository work resolves to the system engineer agent. The root agent is reserved for bootstrap, recovery, project attachment, and platform drift. That one rule prevents a surprising amount of confusion. Most work needs a capable default engineer, not a committee.',
          'Specialists still matter. A planner can shape implementation tasks. A UI debugger can provide browser evidence. A log analyzer can surface operational failures. A strategy-memory analyzer can turn feedback into reusable guidance. The useful pattern is not “ask everyone.” It is “bring in the specialist when the boundary is real.”',
          'The workflow path reinforces this. Normal work runs analysis, context resolution, optional web research when current external facts matter, and planning before execution. Execution then moves through work, validation, feedback, and finalization. The structure gives agents a rhythm that is easy to inspect and improve.'
        ],
      },
      {
        heading: 'Tools become safer when they are part of the pattern',
        paragraphs: [
          'Tools are most helpful when they are predictable. File reads collect context. Tests validate behavior. The UI debugger produces browser evidence. The message bus handles handoffs. The controller plane exposes task, message, workflow, memory, and work-log state. Each tool has a narrow job and a known output.',
          'That is more efficient than asking one model prompt to solve everything inside a single invisible transcript. The agent can use the terminal for source facts, the diagram builder for article diagrams, the debugger for UI evidence, and the controller for durable task visibility. The common thread is that artifacts survive after the step finishes.',
          'The system also avoids premature custom code. New agents should remain declarative unless deterministic Python is truly needed. That keeps behavior discoverable in `agent.yaml`, instructions, workflow YAML, and source maps. When custom code is added, it has to earn its place by handling a repeatable system behavior.'
        ],
      },
      {
        heading: 'Handoffs and gates keep the work honest',
        paragraphs: [
          'The controller-created task flow is a useful example of a gate. Creating the task writes a durable record, but starting the task requires explicit approval. This lets the operator plan and inspect work before execution. Planned task identifiers can be carried into runtime prompts and later updated from final status lines.',
          'Validation is another gate. A compile check proves syntax. Unit tests prove known behavior. Browser evidence proves the UI actually rendered and loaded what it needed. A good collaboration pattern does not collapse these into one vague “done.” It records which claims were verified and which were not.',
          'Feedback closes the loop. After work, strategy feedback can ask whether the result needs rework and whether the lesson should become durable memory. That makes collaboration adaptive without letting every passing opinion become permanent instruction.'
        ],
        diagram: {
          src: 'diagrams/collaboration-gates.html',
          alt: 'Collaboration gates showing planning, approval, implementation, validation evidence, feedback, and finalization.',
          size: 'tall',
        },
      },
      {
        heading: 'Why this is efficient',
        paragraphs: [
          'The system is efficient because it reduces repeated interpretation. Agents are not constantly rediscovering where messages live, how tasks are started, where logs are written, or how memory is injected. Those contracts are stable enough to be reused but transparent enough to be inspected.',
          'It also keeps control local. The runtime owns execution and events. The controller owns visibility and task launch. The MQ server owns cross-component message processing. Memory owns retrieval and extraction policy. When those boundaries are respected, changes are smaller and failures are easier to locate.',
          'That kind of efficiency is not flashy. It is the efficiency of fewer hidden side effects, fewer mystery states, and fewer “it worked in the transcript” claims.'
        ],
      },
      {
        heading: 'The pattern for adding a new collaborator',
        paragraphs: [
          'A new specialist should be added only when it owns a real boundary. If the job is just a different tone of response, it probably belongs in instructions or workflow policy. If the job has a durable input, a repeatable output, its own artifacts, or a different validation surface, then it may deserve its own agent or handler.',
          'The useful questions are straightforward. What request shape does this collaborator accept? What artifacts does it produce? What should it return as a compact reply? Which part of the controller should show its state? Which runtime events or messages make the handoff visible? If those questions have clear answers, the collaborator can fit into the system without making the whole platform harder to understand.',
          'This keeps collaboration from becoming agent sprawl. The system grows by adding clear roles around existing contracts, not by multiplying personalities.'
        ],
      },
    ],
  },
  {
    slug: 'memory-over-time',
    title: 'Memory Over Time: From Runtime Events to Useful Recall',
    kicker: 'Project memory',
    readingTime: '13 min read',
    diagram: 'diagrams/memory.html',
    diagramAlt: 'Runtime events becoming final artifacts, memory candidates, durable records, and retrieved context in future runs.',
    diagramSize: 'tall',
    summary:
      'Memory improves agents when it is derived from real work, bounded during retrieval, and treated as guidance rather than a replacement for current source and user instructions.',
    sections: [
      {
        heading: 'Memory should be earned',
        paragraphs: [
          'A productive memory system does not save everything. Saving everything creates noise, stale advice, and a quiet pressure to trust old context more than current code. This system takes a more careful path: it derives memory candidates from persisted runtime events after a run reaches a terminal state.',
          'The runtime emits `RuntimeEvent` records throughout a run. EventHub persists them under `.agent-state/logs/<session-id>/<run-id>/events.jsonl`. After completion, finalization reads that event stream once and writes `run.json`, `summary.md`, `metrics.json`, `artifacts.json`, and `memory_candidates.json`. Memory candidates come from that evidence, not from a model trying to remember its own conversation.',
          'The current candidate kinds are practical: run summary, failure summary, and change summary. A run summary captures prompt, status, resolved agent, workflow, changed files, artifacts, failures, and final message. A failure summary collects unique failed step, tool, background, and error messages. A change summary records changed files and created artifacts.'
        ],
      },
      {
        heading: 'Retrieval is intentionally bounded',
        paragraphs: [
          'When a future agent step begins, the runtime can ask the memory service for context relevant to the current prompt. Retrieval loads stored records, skips superseded or rejected records, ranks active records, and injects a compact block into developer instructions. The default shape is deliberately small: a handful of hits, each truncated before it can dominate the prompt.',
          'The current implementation uses local lexical scoring with metadata and recency weights. There is no vector store in the runtime today, and that is a reasonable first stage. Lexical retrieval is simple, inspectable, cheap, and good enough for many project-memory cases, especially when records include filenames, agent ids, workflow ids, tags, and concrete failure text.',
          'The system also keeps authority clear. Retrieved memory can help, but current user instructions, current source, and current repository state remain more authoritative. That prevents memory from becoming a ghost architecture.'
        ],
        diagram: {
          src: 'diagrams/memory-retrieval.html',
          alt: 'Retrieval policy showing active records, lexical ranking, filters for stale records, and bounded context injection.',
          size: 'tall',
        },
      },
      {
        heading: 'What belongs in memory',
        paragraphs: [
          'The best memory records are hard to rediscover and likely to matter again. Examples include a known environment failure, a recurring validation command, a directory ownership boundary, a migration decision, or a verified workflow contract. These are the things that save future agents time without telling them to ignore the present.',
          'The worst memory records are generic advice. “Be careful,” “write good tests,” and “check the UI” do not need durable storage. They are habits, not project knowledge. Memory should carry specific evidence: paths, commands, outcomes, and conditions.',
          'A good rule is simple: if the next agent could cheaply rediscover it with one targeted search, it may not need memory. If rediscovering it would require reading old logs, remembering a previous incident, or re-running a fragile scenario, it is a better candidate.'
        ],
      },
      {
        heading: 'Memory as compounding system quality',
        paragraphs: [
          'Over time, this kind of memory changes the first five minutes of work. Instead of starting cold, the agent can see that a build crash may be environment-level, that a controller path moved from an older location, or that browser evidence is expected for UI claims. The agent still verifies current files, but it begins with better hypotheses.',
          'That compounding quality is the point. Memory is not there to make the agent sound confident. It is there to reduce repeated waste, keep local conventions alive, and carry verified lessons forward.'
        ],
      },
      {
        heading: 'How memory should be reviewed',
        paragraphs: [
          'Memory needs stewardship. A record can be accurate when it is written and still become stale after a migration. That is why useful memory systems need status, provenance, and a way to supersede old guidance. The point is not to erase history. The point is to keep future context small, active, and relevant.',
          'A practical review flow starts with source. Where did this memory come from? Was it derived from a completed run, a failure, a change summary, or direct operator feedback? Then it checks usefulness. Would this help a future agent avoid real waste? Finally, it checks authority. Is this a durable practice, a temporary workaround, or a detail that current source should decide?',
          'This review habit protects the system from memory drift. The agent becomes more informed over time, but the repository remains the thing that decides what is true today.'
        ],
      },
    ],
  },
  {
    slug: 'feedback-loop-memory',
    title: 'The Feedback Loop That Makes Memory Better',
    kicker: 'Operator learning',
    readingTime: '12 min read',
    diagram: 'diagrams/feedback.html',
    diagramAlt: 'Work result, human feedback, analyzer, strategy memory, rework, and future agent planning loop.',
    diagramSize: 'tall',
    summary:
      'Feedback turns memory from passive recall into a living strategy layer, especially when rework, analyzer decisions, and superseded guidance are handled explicitly.',
    sections: [
      {
        heading: 'Completion is not always the end',
        paragraphs: [
          'Agent work often reaches a point where tests pass and the final answer is written, but the operator still has a better strategy in mind. Maybe the agent validated the wrong thing. Maybe it wrote too much documentation. Maybe it should have used a local tool earlier. The feedback loop gives that judgment a structured place to go.',
          'The runtime includes a strategy feedback coordinator that can run after work and validation and before finalization when that path is enabled or invoked. The hook can collect operator feedback, ask whether rework is needed, and ask whether the guidance should be stored as durable strategy memory. That timing is useful because the run still has enough context to act on the feedback, but the final artifacts have not yet been sealed.',
          'If rework is requested, the runtime can run a bounded rework turn and ask for feedback again. This avoids the trap where feedback becomes a note for next time while the current result remains unsatisfying.'
        ],
      },
      {
        heading: 'From human note to strategy memory',
        paragraphs: [
          'Submitted feedback is written as a run artifact. Then the strategy-memory analyzer classifies it and proposes memory actions. Those actions can add, update, supersede, or skip records. The memory service validates the actions before writing records under `.agent-state/cache/memory/records/strategy/`.',
          'There is also a practical fallback. If the user requested storage but the analyzer produces no memory action, the runtime can create a local feedback-derived memory action. That protects the operator from losing useful guidance because an analyzer was too conservative.',
          'Older strategy records are not simply deleted. They can be marked superseded. That keeps history while preventing stale guidance from being injected into future prompts.'
        ],
        diagram: {
          src: 'diagrams/feedback-rework.html',
          alt: 'Feedback detail showing submitted feedback becoming analyzer actions, strategy memory, optional rework, and superseded history.',
          size: 'tall',
        },
      },
      {
        heading: 'Why feedback improves the memory system',
        paragraphs: [
          'Event-derived memory tells the system what happened. Strategy feedback tells it how the user wants future work to be done. Both are needed. A run summary might say which files changed and which tests passed. Feedback might say that browser validation should include mobile screenshots for this UI, or that agent-created controller tasks must wait for explicit approval.',
          'This makes memory more personal and more operational. It captures the user’s standards, not just the runtime’s facts. Over time, agents can become more aligned with the way the project is actually run.',
          'The key is restraint. Not every comment should become durable strategy. Good feedback memory is reusable, project-specific, and connected to observed work. The system should remember the lesson, not the mood of the moment.'
        ],
      },
      {
        heading: 'A healthier loop',
        paragraphs: [
          'The loop is healthiest when each stage has a job. Work produces evidence. Feedback evaluates the evidence. The analyzer converts reusable guidance into memory actions. Rework applies urgent corrections. Future retrieval brings the active guidance back when it is relevant.',
          'That creates a calm improvement cycle. Agents do not need to be perfect on the first pass to become better. They need to listen, revise, and preserve the lessons that are worth carrying forward.'
        ],
      },
      {
        heading: 'Feedback needs to stay specific',
        paragraphs: [
          'The best feedback is concrete enough to change future behavior. “Do better validation” is a mood. “For UI changes, run a browser check and mention screenshot, console, and network evidence separately” is a reusable strategy. The second version can become memory because it gives the next agent a clear action and a clear reporting standard.',
          'Specific feedback also helps rework. If the operator says the agent missed the route-refresh case, the rework step can target routing. If the operator says the article tone feels generic, the rework step can rewrite the introduction around the intended audience and voice. Feedback becomes useful when it names the gap, the expected behavior, and the evidence that would prove the fix.',
          'This is why the feedback loop is part of the system rather than an afterthought. It gives human judgment a durable, structured path back into the agent runtime.'
        ],
      },
    ],
  },
  {
    slug: 'logging-systems',
    title: 'Logging Systems That Help Instead of Haunting the Project',
    kicker: 'Observability',
    readingTime: '12 min read',
    diagram: 'diagrams/logging.html',
    diagramAlt: 'Browser logs, backend logs, Python runtime logs, runtime events, log analyzer, and operational error message flow.',
    diagramSize: 'tall',
    summary:
      'Useful logging separates diagnostics, runtime events, browser evidence, and operational errors so each one answers a different question.',
    sections: [
      {
        heading: 'Logs are not the same as events',
        paragraphs: [
          'The system keeps a clean distinction between runtime events and diagnostic logs. Runtime events are the durable state contract for a run: started, resolved, workflow events, file changes, artifacts, failures, and terminal status. Diagnostic logs are there for application behavior around the runtime: backend requests, Python package diagnostics, browser errors, and health checks.',
          'That separation prevents logs from becoming the only source of truth. A client should not parse a JSONL log file from the browser and try to reconstruct runtime state. It should consume structured snapshots or event streams. Logs remain valuable, but they answer a different question: what did the application observe while trying to do its job?',
          'This design makes finalization cleaner. Memory candidates and run artifacts come from persisted runtime events, while log analyzer findings become operational error messages when they require attention.'
        ],
      },
      {
        heading: 'Daily logs with bounded detail',
        paragraphs: [
          'The controller API writes daily logs under `.agent-state/logs/system/controller/`. Entries include timestamp, source, level, message, and bounded details. Browser logging uses a backend endpoint so console errors, rejected promises, failed fetch calls, and failed XHR calls can be captured without asking the operator to copy from DevTools.',
          'The runtime has its own Python diagnostics under `.agent-state/logs/system/runtime/`, and messaging has system logs under `.agent-state/logs/system/messaging/`. Health checks write their latest state under `.agent-state/logs/system/health/latest.json`. Each stream has a location and a purpose.',
          'The important habit is to log what will help root-cause analysis. A useful log line has a source, a level, and enough details to connect it to a request or file. A noisy log line just teaches everyone to stop reading.'
        ],
      },
      {
        heading: 'The log analyzer closes the visibility gap',
        paragraphs: [
          'The optional log analyzer watches fresh system log lines for `ERROR` entries. When it finds one, it builds an exact error object with type, source, observed timestamp, relative path, line number, exact log line, and nearby context. That object is passed into the messaging system as an operational error.',
          'This is a strong pattern because logs become actionable without becoming memory by default. The controller can show the current active error. Agents can see an `error.detected` message. Once the fix is verified, the error can be resolved and archived.',
          'The system therefore does not depend on someone remembering that a scary line appeared in a terminal. If it matters, it becomes visible state.'
        ],
        diagram: {
          src: 'diagrams/logging-error-routing.html',
          alt: 'Error routing detail showing system logs, analyzer context, current-error state, error.detected message, and fixed archive.',
          size: 'tall',
        },
      },
      {
        heading: 'Evidence belongs in layers',
        paragraphs: [
          'Different evidence answers different questions. A build log answers whether the compiler accepted the code. A unit test log answers whether known behavior still holds. A runtime event stream answers what the agent workflow did. A browser screenshot answers what a user would see. Network errors answer which requests failed in the browser.',
          'Good observability lets those layers support each other without mixing them into one blob. The article site itself follows that habit: build output verifies production compilation, while a browser check should verify rendered layout and route behavior.',
          'The result is a logging system that helps rather than haunts. It keeps enough detail to debug, enough structure to display, and enough restraint to stay readable.'
        ],
      },
      {
        heading: 'What a useful log should tell the next agent',
        paragraphs: [
          'A useful log should help the next agent answer three questions quickly: what happened, where did it happen, and what should be checked next? That means a source label, a level, a timestamp, a bounded detail object, and enough context to connect the line to a run, request, path, or browser route.',
          'The system should avoid two extremes. Too little logging forces agents to guess. Too much logging turns every investigation into archaeology. The middle path is structured, bounded, and connected to artifacts. A log line can point to a screenshot, a runtime event can point to a changed file, and an error message can point to the active error record.',
          'When logs are designed this way, they become part of the agent workflow. They are not just developer leftovers. They are a communication layer between the past run and the next person or agent trying to understand it.'
        ],
      },
    ],
  },
  {
    slug: 'controller-plane',
    title: 'The Controller Plane: A Window Into Agent Work',
    kicker: 'Control surface',
    readingTime: '13 min read',
    diagram: 'diagrams/controller-plane.html',
    diagramAlt: 'Angular controller UI, Nest controller API, MQ server, runtime, workflows, memory, messages, logs, and artifacts.',
    diagramSize: 'tall',
    summary:
      'The controller plane is most useful when it stays a control and visibility layer, while the runtime remains the owner of workflow execution.',
    sections: [
      {
        heading: 'A controller should not become a second runtime',
        paragraphs: [
          'The controller exists to make agent work visible and operable. It should show tasks, agents, workflows, messages, memory, logs, and active errors. It should let the user create and approve work. It should expose details without asking the browser to understand raw repository files. But it should not quietly become the place where workflow logic lives.',
          'In this system, the Nest controller API reads repository-backed state and launches task runner processes. The Python runtime owns execution. That boundary matters. If the UI starts duplicating workflow resolution, finalization, or memory behavior, the platform becomes harder to reason about. One run could mean different things depending on where it started.',
          'The controller is therefore a window and a set of safe controls. It is not the engine.'
        ],
      },
      {
        heading: 'What the controller plane owns',
        paragraphs: [
          'The controller plane owns path discovery, safe file persistence, health checks, and Git-driven change-impact evaluation. Its path map is a source of truth for important runtime, state, and controller paths. Its data store conventions describe messages, tasks, plans, sessions, and work logs.',
          'The API exposes structured endpoints for snapshots, agents, skills, workflows, tasks, memory, work logs, messaging, message threads, and browser/backend logs. The Angular UI consumes those endpoints and renders operator views. The browser receives structured JSON, not a filesystem scavenger hunt.',
          'That design lets the UI stay responsive and inspectable. A malformed memory record can be skipped with a warning instead of breaking the whole page. A task record can show its message id and events. A messaging snapshot can include totals, pending records, task statuses, active errors, and recent lifecycle events.'
        ],
      },
      {
        heading: 'Task launch is intentionally explicit',
        paragraphs: [
          'One of the controller’s best design choices is separating task creation from task launch. Creating a task writes the `task_request` message and a task record with status awaiting implementation. Starting it requires an explicit approval call. That approval appends a task event and then launches the task runner.',
          'This is practical operator design. Users can queue work, review it, and start it when they are ready. Agents do not begin expensive or risky work just because a card was created. The task thread reflects the real lifecycle.',
          'When the task runner replies, the controller can show the result as part of the same message thread. The UI stays close to the facts.'
        ],
        diagram: {
          src: 'diagrams/controller-task-launch.html',
          alt: 'Controller task lifecycle showing create task, await approval, start task, task runner, runtime gateway, and result reply.',
          size: 'tall',
        },
      },
      {
        heading: 'Why the controller plane makes the system calmer',
        paragraphs: [
          'Agent systems can feel chaotic when everything happens inside invisible transcripts. The controller plane calms that down. It gives the operator a place to see who is available, what is queued, which workflow ran, what memory exists, what logs say, and which operational error is active.',
          'The calmer experience comes from respecting the boundary. The runtime can evolve. The MQ server can handle deterministic actions. The memory service can improve retrieval. The UI can refine its views. Each piece gets better without taking ownership from the others.',
          'That is the controller plane’s real job: make the work legible while keeping the system’s authority in the right place.'
        ],
      },
      {
        heading: 'Designing the controller for operators',
        paragraphs: [
          'The controller should be built for repeat work, not spectacle. The operator needs to scan pending tasks, active errors, messages, memory records, and recent runs quickly. That means dense but readable views, stable route structure, clear statuses, and links from summary cards to the underlying records.',
          'A good controller does not hide uncertainty. If a task is awaiting approval, it should say so. If a debugger run failed to start Chrome, that failure should be visible. If a memory record is superseded, it should not appear as active guidance. If a backend skips malformed state, the UI should continue while the logs explain what happened.',
          'This operator-first design is what lets the controller improve the agent system without taking over the runtime. It gives people a reliable place to inspect and steer the work.'
        ],
      },
    ],
  },
  {
    slug: 'future-memory-integrations',
    title: 'Future Memory and Integrations for Smarter Agent Systems',
    kicker: 'Roadmap',
    readingTime: '12 min read',
    diagram: 'diagrams/future-memory.html',
    diagramAlt: 'Current event-derived memory expanding into lexical recall, vector memory, external integrations, provenance checks, and bounded prompt injection.',
    diagramSize: 'tall',
    summary:
      'Vector memory and external integrations can make agents smarter, but only if provenance, authority, and bounded retrieval remain first-class design rules.',
    sections: [
      {
        heading: 'Start from what already works',
        paragraphs: [
          'The current memory system has a strong base: durable runtime events, deterministic candidates, local records, lexical retrieval, strategy feedback, and clear prompt injection boundaries. That base should stay. Future memory should extend it, not replace it with a black box.',
          'The reason is trust. An agent should be able to say where a memory came from. Was it derived from a completed run? Was it submitted through operator feedback? Was it pulled from a design doc, issue tracker, chat thread, or code review? Without provenance, memory becomes a confident rumor.',
          'Good future integration begins with a simple promise: every retrieved memory has a source, a timestamp, a status, and a reason it was selected.'
        ],
      },
      {
        heading: 'Where vector memory fits',
        paragraphs: [
          'Vector memory is useful when exact words are not enough. Lexical retrieval is good at matching paths, symbols, errors, and explicit tags. Vector retrieval can help with conceptual similarity: a past decision about “operator approval before execution” may be relevant even when the new prompt says “do not auto-run user-created tasks.”',
          'The right design is probably hybrid. Lexical retrieval should remain the precise layer. Vector search can propose semantically related records. A reranker or policy layer can then enforce status, recency, source boundaries, and injection limits. The final prompt should still receive a compact explanation, not a heap of loosely related notes.',
          'Vector memory should also be scoped. Project memory, strategy memory, documentation memory, and external-ticket memory may have different freshness and authority. A codebase fact from yesterday should outrank a six-month-old chat summary unless the older item is explicitly marked as durable policy.'
        ],
      },
      {
        heading: 'Different memory types deserve different rules',
        paragraphs: [
          'Run memory records what happened. Failure memory records what broke and how it presented. Change memory records files and artifacts. Strategy memory records how the user wants agents to work. Architecture memory records decisions and boundaries. External memory could summarize issues, pull requests, docs, incident notes, design systems, and support threads.',
          'Those should not all be thrown into one ranking bucket. A future system can improve by giving each type a policy: how it is created, how it expires, how it is superseded, who can approve it, and how much of it can enter a prompt.',
          'This is especially important for public or team-facing integrations. A GitHub issue may contain speculation. A design doc may be authoritative. A Slack message may be useful but informal. The retrieval layer has to preserve those differences.'
        ],
        diagram: {
          src: 'diagrams/future-memory-types.html',
          alt: 'Future memory type map showing run, failure, strategy, architecture, vector, and external memory with separate policies.',
          size: 'tall',
        },
      },
      {
        heading: 'Integration without losing control',
        paragraphs: [
          'The most promising integrations are the ones that fit the existing control-plane pattern. External sources can be ingested into candidate records. Candidate records can be reviewed, tagged, ranked, and bounded. Agents can retrieve them through the same context assembly path rather than gaining uncontrolled access to every connected system.',
          'The controller can help here. It can show memory sources, active and superseded records, candidate status, and retrieval previews. Feedback can correct bad memories and preserve good strategy. Logging can show when retrieval fails or when an external source is unavailable.',
          'Future memory will make the system smarter only if it keeps the current discipline: durable evidence, clear provenance, bounded injection, and current source as the final authority. That is how the system can grow more capable without becoming mysterious.'
        ],
      },
      {
        heading: 'What smarter memory should feel like',
        paragraphs: [
          'The best future memory will feel quiet. The agent should not flood the prompt with every related idea. It should retrieve a small set of records that explain why they matter: a similar past failure, a relevant architecture rule, a known validation habit, or a user strategy preference that applies to the current work.',
          'Vector memory can help find related ideas, but the final experience should still be simple. The agent should be able to say, in plain language, which memories influenced the plan and which files or checks will verify the current truth. That explanation is what keeps semantic retrieval from becoming mysterious.',
          'The long-term direction is a system where different memory types work together: exact lexical matches for paths and errors, vector recall for concepts, strategy memory for user preferences, architecture memory for boundaries, and external memory for issue or documentation context. The value comes from coordination, not from any single storage technique.'
        ],
      },
    ],
  },
];
