export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
export type AppRequest<TPayload = unknown> = { readonly endpoint: string; readonly method: HttpMethod; readonly payload?: TPayload };
export type AppResponse<TData = unknown> = { readonly success: boolean; readonly status: number; readonly message: string; readonly data: TData; readonly timestamp: string };

export type TaskStatus = 'awaiting implementation' | 'implementing' | 'complete' | 'need rework';
export type TaskEvent = { ts: string; type: string; status?: string; message: string; details?: Record<string, unknown> };
export type Task = { id: string; title: string; summary: string; status: TaskStatus; label?: string; date: string; tokens: number; plan: string; owner: string; agentId: string; duration: string; prompt: string; messageId?: string; messagePath?: string; runId?: string; sessionId?: string; createdAt: string; updatedAt: string; events: TaskEvent[]; source?: string; planId?: string; planTitle?: string; plannedTaskId?: string; taskPath?: string; tasksYamlPath?: string; description?: string; files?: string[]; dependsOn?: string[]; acceptanceCriteria?: string[] };
export type Agent = { id: string; name: string; role: string; status: string; summary: string; workflow: string; tools: string[]; aliases: string[]; instructionsPath: string; skills: string[]; history: string[]; performance: { label: string; value: string }[] };
export type Skill = { id: string; name: string; category: string; summary: string; content: string; path: string; assignedAgents: string[] };
export type WorkflowStep = { id: string; name: string; uses: string; agent?: string; tool?: string; command?: string };
export type Workflow = { id: string; name: string; status: string; runs: string; owner: string; description: string; phase: string; steps: WorkflowStep[] };
export type MemoryEntry = { id: string; title: string; kind: string; status: string; updated: string; excerpt: string; content?: string; path: string; runId?: string; sessionId?: string; tags: string[]; metadata?: Record<string, unknown> };
export type WorkLog = { id: string; date: string; event: string; agent: string; detail: string; status?: string; path?: string };
export type MessageRecord = { id: string; created_at: string; updated_at: string; sender: string; recipient: string; type: string; reply_to?: string | null; status: string; path: string; folder_agent_id: string; payload?: Record<string, unknown>; error?: string };
export type OperationalErrorRecord = { id: string; status: string; fingerprint: string; created_at: string; updated_at: string; occurrence_count?: number; error?: Record<string, unknown>; history?: Record<string, unknown>[]; resolution?: Record<string, unknown> };
export type MessagingSummary = { root: string; manifest: string; eventLog: string; total: number; tasks: number; unresolved: number; activeErrors: number; currentError?: OperationalErrorRecord | null; byStatus: Record<string, number>; byType: Record<string, number>; taskStatuses: Record<string, number>; agents: string[] };
export type MessagingSnapshot = { summary: MessagingSummary; messages: MessageRecord[]; events: Record<string, unknown>[]; errors: OperationalErrorRecord[] };
export type ControllerSnapshot = { agents: Agent[]; tasks: Task[]; skills: Skill[]; workflows: Workflow[]; memory: MemoryEntry[]; workLogs: WorkLog[]; messaging: MessagingSnapshot };
export type CreateTaskRequest = { title?: string; prompt: string; agentId?: string; planId?: string; planTitle?: string; plannedTaskId?: string };
export type CreateSkillRequest = { id: string; name?: string; category?: string; summary?: string; content?: string; assignToAgentIds?: string[] };
export type CreateMessageRequest = { sender?: string; recipient: string; type: string; payload?: Record<string, unknown>; replyTo?: string };
